select * from INMATES_STMT_INFO

insert into INMATES_STMT_INFO
	OFFENDER_ID, 
	OVERRIDE_MONTHLY_AMT_DUE, 
	OVERRIDE_CURRENT_AMT_DUE, 
	LAST_PAYMENT_DATE, 
	LAST_PAYMENT_AMT, 
	LAST_STMT_AMT_DUE
values
	v_offender_id,
	0.00,
	0.00
	null,
	null,
	null   
	
insert into inmates
select	OFFENDER_ID, 
	NAME_FIRST, 
	NAME_OTHER, 
	NAME_FAMILY, 
	
	  STREET, 
	  CITY_TOWN_LOCALE, 
	  STATE_PROVINCE_REGION, 
	  POSTAL_CODE, 
	  PHONE_NUMBER, 
	  ALTERNATIVE_PHONE_NUMBER, 
	  DATE_OF_BIRTH, 
	  SOCIAL_SECURITY_NUMBER, 
	  DRIVERS_LICENSE_NUMBER, 
	MODIFIED_BY, 
	MODIFIED_DATE, 
	ACCOUNT_STATUS_ID, -- lookup from ACCOUNT_STATUS_TYPES
	'yes' as IS_VALID_ADDRESS, 
	'no' as IS_LEGAL_JUDGEMENT, 
	'no' as IS_COLLECTIONS, 
	'no' as IS_LEGACY_DATA, 
	'no' as IS_LEGACY_CORRECTED
		