insert into users
select USER_INT_ID, USER_ID, 'qwe123', USER_NAME_LAST, USER_NAME_FIRST, USER_NAME_MIDDLE, USER_NAME_SUFFIX, JOB_TITLE, DATE_START, DATE_END, ACTION_TYPE, ACTION_TIME, ACTION_BY, decode(date_end,null,'Y','N'),null
from epic.EPIC_USER_NAMES
