REM Note that this DDL is not guaranteed to include
REM   all properties of the original object.  It will also
REM   not include CLUSTER or PARTITION information.  Please
REM   report any other problems to support@benthicsoftware.com
CREATE TABLE EH_TEMP_MATCHING_OFFENDERS (
	REQUEST_ID   CHAR(16) NOT NULL,
	IDENTITY_ID  CHAR(16) NOT NULL,
	SCORE        NUMBER(38) NOT NULL)
	PCTFREE 10 INITRANS 1 MAXTRANS 255
	STORAGE (INITIAL 65536 MINEXTENTS 1 MAXEXTENTS 2147483645 BUFFER_POOL DEFAULT)
	TABLESPACE MACOMB;



REM Note that this DDL is not guaranteed to include
REM   all properties of the original object.  It will also
REM   not include CLUSTER or PARTITION information.  Please
REM   report any other problems to support@benthicsoftware.com
CREATE TABLE LEGACY_MUGSHOTS (
	INMATE_NAME    VARCHAR2(30) NOT NULL,
	INMATE_NUMBER  NUMBER(8) NOT NULL,
	PHOTO_DATE     DATE NOT NULL,
	DOB            DATE NOT NULL,
	SEX            VARCHAR2(1) NOT NULL,
	RACE           VARCHAR2(3) NOT NULL,
	HAIR           VARCHAR2(3) NOT NULL,
	EYES           VARCHAR2(3) NOT NULL,
	WEIGHT         NUMBER(3) NOT NULL,
	HEIGHT         NUMBER(3) NOT NULL,
	FILE_NAME      VARCHAR2(255) NOT NULL)
	PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
	STORAGE (INITIAL 5242880 NEXT 5242880 MINEXTENTS 1 MAXEXTENTS 2147483645 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
	TABLESPACE LEGACY_DATA;

ALTER TABLE LEGACY_MUGSHOTS ADD (
	CONSTRAINT LEGACY_MUGSHOTS_PK PRIMARY KEY (INMATE_NUMBER, PHOTO_DATE, FILE_NAME)
		USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
		STORAGE (INITIAL 65536 MINEXTENTS 1 MAXEXTENTS 2147483645 BUFFER_POOL DEFAULT)
		TABLESPACE MACOMB);


REM Note that this DDL is not guaranteed to include
REM   all properties of the original object.  It will also
REM   not include CLUSTER or PARTITION information.  Please
REM   report any other problems to support@benthicsoftware.com
CREATE TABLE MACOMBSIGNAL (
	SIGNAME   VARCHAR2(32) NOT NULL,
	PROGNAME  VARCHAR2(32) NOT NULL)
	PCTFREE 10 INITRANS 1 MAXTRANS 255
	STORAGE (INITIAL 65536 MINEXTENTS 1 MAXEXTENTS 2147483645 BUFFER_POOL DEFAULT)
	TABLESPACE MACOMB;

ALTER TABLE MACOMBSIGNAL ADD (
	CONSTRAINT PRSIG_CHK_PRNAME1 CHECK (upper(ProgName)= ProgName),
	CONSTRAINT PRSIG_CHK_SIGNAME1 CHECK (upper(signame)= signame));

CREATE UNIQUE INDEX PROGSIGNALPKI ON MACOMBSIGNAL (PROGNAME, SIGNAME)
	PCTFREE 10 INITRANS 2 MAXTRANS 255
	STORAGE (INITIAL 65536 MINEXTENTS 1 MAXEXTENTS 2147483645 BUFFER_POOL DEFAULT)
	TABLESPACE MACOMB;


REM Note that this DDL is not guaranteed to include
REM   all properties of the original object.  It will also
REM   not include CLUSTER or PARTITION information.  Please
REM   report any other problems to support@benthicsoftware.com
CREATE TABLE MASH_ARREST (
	ARREST_ID         VARCHAR2(16) NOT NULL,
	ARREST_DATETIME   DATE NOT NULL,
	ARREST_WITH_ID    VARCHAR2(16) NOT NULL,
	ARREST_LOCATION   VARCHAR2(64) NOT NULL,
	ARREST_CITY       VARCHAR2(64) NOT NULL,
	ARREST_STATE      VARCHAR2(2) NOT NULL,
	ARREST_PREVHELD   VARCHAR2(64) NOT NULL,
	ARREST_HELD_LOC   VARCHAR2(64) NOT NULL,
	VEHICLE_TOWED_TO  VARCHAR2(255) NOT NULL)
	PCTFREE 10 INITRANS 1 MAXTRANS 255
	STORAGE (INITIAL 65536 MINEXTENTS 1 MAXEXTENTS 2147483645 BUFFER_POOL DEFAULT)
	TABLESPACE MACOMB;


REM Note that this DDL is not guaranteed to include
REM   all properties of the original object.  It will also
REM   not include CLUSTER or PARTITION information.  Please
REM   report any other problems to support@benthicsoftware.com
CREATE TABLE MASH_EVENT_LOG (
	EVENT_ID    NUMBER(10) NOT NULL,
	EVENT_DATE  DATE NOT NULL,
	EVENT_DESC  VARCHAR2(64) NOT NULL,
	EVENT_TYPE  VARCHAR2(4) NOT NULL)
	PCTFREE 10 INITRANS 1 MAXTRANS 255
	STORAGE (INITIAL 65536 MINEXTENTS 1 MAXEXTENTS 2147483645 BUFFER_POOL DEFAULT)
	TABLESPACE MACOMB;


REM Note that this DDL is not guaranteed to include
REM   all properties of the original object.  It will also
REM   not include CLUSTER or PARTITION information.  Please
REM   report any other problems to support@benthicsoftware.com
CREATE TABLE MCMB_GVT_IN (
	OFFENDER_ID   VARCHAR2(64),
	RMBSMT_BAL    NUMBER(11,2),
	LEGAL_FLAG    CHAR(1),
	LEGAL_AMOUNT  NUMBER(11,2))
	PCTFREE 10 INITRANS 1 MAXTRANS 255
	STORAGE (INITIAL 65536 MINEXTENTS 1 MAXEXTENTS 2147483645 BUFFER_POOL DEFAULT)
	TABLESPACE MACOMB;


REM Note that this DDL is not guaranteed to include
REM   all properties of the original object.  It will also
REM   not include CLUSTER or PARTITION information.  Please
REM   report any other problems to support@benthicsoftware.com
CREATE TABLE MCMB_TABLE_RDC (
	CELLNAME  VARCHAR2(4000),
	LOCATION  VARCHAR2(22),
	CAPACITY  NUMBER,
	HSLINK    VARCHAR2(255))
	PCTFREE 10 INITRANS 1 MAXTRANS 255
	STORAGE (INITIAL 65536 MINEXTENTS 1 MAXEXTENTS 2147483645 BUFFER_POOL DEFAULT)
	TABLESPACE MACOMB;


REM Note that this DDL is not guaranteed to include
REM   all properties of the original object.  It will also
REM   not include CLUSTER or PARTITION information.  Please
REM   report any other problems to support@benthicsoftware.com
CREATE TABLE MMV_ACTIVE_CHARGE (
	ENTITY_ID           CHAR(16),
	OFFENDER_ID         VARCHAR2(4000),
	CHARGE_ID           CHAR(16),
	STATUTE_ID          CHAR(16),
	PACC                VARCHAR2(64),
	CHARGE_DESC         VARCHAR2(255),
	CHARGE_CLASS        VARCHAR2(4000),
	SENTENCE_ID         CHAR(16),
	CHARGE_ID_NUMBER    VARCHAR2(4000),
	AGENCY_ID           VARCHAR2(16),
	COMPLAINT_DEPT      VARCHAR2(255),
	COURT_ID            CHAR(16),
	CASE_NO             VARCHAR2(4000),
	COURT_NAME          VARCHAR2(4000),
	COURT_DATE          VARCHAR2(10),
	COURT_DIVISION      VARCHAR2(4000),
	COURT_JUDGE         VARCHAR2(4000),
	START_DATE          DATE,
	FINAL_RELEASE_DATE  DATE,
	AMOUNT              NUMBER,
	AMOUNT_TYPE         VARCHAR2(4),
	TRANS_TYPE          VARCHAR2(1),
	SORTORDER           NUMBER,
	WEB_CHARGE_PK       VARCHAR2(4000),
	REDUCEAMOUNT        VARCHAR2(1),
	PAIDOUTDATE         DATE,
	UNPAIDOUTDATE       DATE)
	PCTFREE 10 INITRANS 1 MAXTRANS 255
	STORAGE (INITIAL 65536 MINEXTENTS 1 MAXEXTENTS 2147483645 BUFFER_POOL DEFAULT)
	TABLESPACE MACOMB;

COMMENT ON TABLE MMV_ACTIVE_CHARGE IS 'snapshot table for snapshot MACOMB.MMV_ACTIVE_CHARGE';


REM Note that this DDL is not guaranteed to include
REM   all properties of the original object.  It will also
REM   not include CLUSTER or PARTITION information.  Please
REM   report any other problems to support@benthicsoftware.com
CREATE TABLE MT_JCS_HISTORY (
	CELL    VARCHAR2(64),
	RDC     NUMBER(3),
	COUNT   NUMBER(5),
	DATETM  DATE,
	SORT    VARCHAR2(8))
	PCTFREE 10 INITRANS 1 MAXTRANS 255
	STORAGE (INITIAL 65536 MINEXTENTS 1 MAXEXTENTS 2147483645 BUFFER_POOL DEFAULT)
	TABLESPACE MACOMB;

ALTER TABLE MT_JCS_HISTORY ADD (
	PRIMARY KEY (CELL, DATETM)
		USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
		STORAGE (INITIAL 65536 MINEXTENTS 1 MAXEXTENTS 2147483645 BUFFER_POOL DEFAULT)
		TABLESPACE MACOMB);


REM Note that this DDL is not guaranteed to include
REM   all properties of the original object.  It will also
REM   not include CLUSTER or PARTITION information.  Please
REM   report any other problems to support@benthicsoftware.com
CREATE TABLE MT_JCS_MONTHLY (
	CELL    VARCHAR2(64),
	RDC     VARCHAR2(8),
	COUNT   VARCHAR2(8),
	DATETM  DATE,
	SORT1   VARCHAR2(16),
	SORT2   VARCHAR2(16),
	SORT3   VARCHAR2(16))
	PCTFREE 10 INITRANS 1 MAXTRANS 255
	STORAGE (INITIAL 65536 MINEXTENTS 1 MAXEXTENTS 2147483645 BUFFER_POOL DEFAULT)
	TABLESPACE MACOMB;


REM Note that this DDL is not guaranteed to include
REM   all properties of the original object.  It will also
REM   not include CLUSTER or PARTITION information.  Please
REM   report any other problems to support@benthicsoftware.com
CREATE TABLE MT_JCS_RDC (
	CELLNAME  VARCHAR2(255),
	LOCATION  VARCHAR2(22),
	CAPACITY  NUMBER,
	HSLINK    VARCHAR2(255))
	PCTFREE 10 INITRANS 1 MAXTRANS 255
	STORAGE (INITIAL 65536 MINEXTENTS 1 MAXEXTENTS 2147483645 BUFFER_POOL DEFAULT)
	TABLESPACE MACOMB;


REM Note that this DDL is not guaranteed to include
REM   all properties of the original object.  It will also
REM   not include CLUSTER or PARTITION information.  Please
REM   report any other problems to support@benthicsoftware.com
CREATE TABLE MT_JIL_ALIAS (
	ENTITY_ID_FK    VARCHAR2(16) NOT NULL,
	OFFENDER_ID     VARCHAR2(64) NOT NULL,
	ALIAS_ID_PK     VARCHAR2(16) NOT NULL,
	LASTNAME        VARCHAR2(64),
	FIRSTNAME       VARCHAR2(64),
	MIDDLENAME      VARCHAR2(64),
	SUFFIXNAME      VARCHAR2(64),
	DOB             VARCHAR2(11),
	CODE_NAME_TYPE  VARCHAR2(64))
	PCTFREE 10 INITRANS 1 MAXTRANS 255
	STORAGE (INITIAL 65536 MINEXTENTS 1 MAXEXTENTS 2147483645 BUFFER_POOL DEFAULT)
	TABLESPACE MACOMB;

ALTER TABLE MT_JIL_ALIAS ADD (
	CONSTRAINT ALIAS_PK PRIMARY KEY (ALIAS_ID_PK)
		USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
		STORAGE (INITIAL 65536 MINEXTENTS 1 MAXEXTENTS 2147483645 BUFFER_POOL DEFAULT)
		TABLESPACE MACOMB,
	CONSTRAINT FK_ALIAS_COMP FOREIGN KEY (ENTITY_ID_FK) REFERENCES MT_JIL_INMATE (ENTITY_ID_PK));


REM Note that this DDL is not guaranteed to include
REM   all properties of the original object.  It will also
REM   not include CLUSTER or PARTITION information.  Please
REM   report any other problems to support@benthicsoftware.com
CREATE TABLE MT_JIL_CHARGE (
	ENTITY_ID_FK        VARCHAR2(16) NOT NULL,
	OFFENDER_ID         VARCHAR2(64) NOT NULL,
	DISPOSEDATE         DATE,
	DISPOSEREASON       VARCHAR2(64),
	CHARGE_ID           VARCHAR2(16),
	STATUTE_ID          VARCHAR2(64),
	PACC                VARCHAR2(64),
	CHARGE_DESC         VARCHAR2(255),
	CHARGE_CLASS        VARCHAR2(64),
	SENTENCE_ID         VARCHAR2(16),
	CHARGE_ID_NUMBER    VARCHAR2(64),
	AGENCY_ID           VARCHAR2(16),
	COMPLAINT_DEPT      VARCHAR2(64),
	COURT_ID            VARCHAR2(16),
	CASE_NO             VARCHAR2(64),
	COURT_NAME          VARCHAR2(64),
	COURT_DATE          VARCHAR2(10),
	COURT_DIVISION      VARCHAR2(64),
	JUDGE               VARCHAR2(64),
	START_DATE          DATE,
	FINAL_RELEASE_DATE  DATE,
	AMOUNT              NUMBER(20,2),
	AMOUNT_TYPE         CHAR(10),
	TRANS_TYPE          CHAR(1),
	SORT_ORDER          CHAR(1),
	REDUCEAMOUNT        CHAR(1),
	PAIDOUTDATE         DATE,
	UNPAIDOUTDATE       DATE,
	SURCHARGE_AMOUNT    NUMBER(20,2),
	CHARGE_STATE        VARCHAR2(64))
	PCTFREE 10 INITRANS 1 MAXTRANS 255
	STORAGE (INITIAL 65536 MINEXTENTS 1 MAXEXTENTS 2147483645 BUFFER_POOL DEFAULT)
	TABLESPACE MACOMB;

ALTER TABLE MT_JIL_CHARGE ADD (
	CONSTRAINT CHARGE_PK PRIMARY KEY (ENTITY_ID_FK, CHARGE_ID)
		USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
		STORAGE (INITIAL 65536 MINEXTENTS 1 MAXEXTENTS 2147483645 BUFFER_POOL DEFAULT)
		TABLESPACE MACOMB,
	CONSTRAINT FK_CHARGE_ENTITY_ID FOREIGN KEY (ENTITY_ID_FK) REFERENCES MT_JIL_INMATE (ENTITY_ID_PK));


REM Note that this DDL is not guaranteed to include
REM   all properties of the original object.  It will also
REM   not include CLUSTER or PARTITION information.  Please
REM   report any other problems to support@benthicsoftware.com
CREATE TABLE MT_JIL_INMATE (
	ENTITY_ID_PK       VARCHAR2(16) NOT NULL,
	ACTIVE             VARCHAR2(1) NOT NULL,
	OFFENDER_ID        VARCHAR2(64) NOT NULL,
	JUVENILE_FLAG      VARCHAR2(1) NOT NULL,
	INMATECLASS        VARCHAR2(1),
	LASTNAME           VARCHAR2(32),
	FIRSTNAME          VARCHAR2(32),
	OTHERNAME          VARCHAR2(64),
	DOB                VARCHAR2(11),
	GENDER             VARCHAR2(64),
	CELL               VARCHAR2(10),
	LEVEL4             VARCHAR2(40),
	LEVEL5             VARCHAR2(40),
	LEVEL6             VARCHAR2(40),
	LEVEL7             VARCHAR2(40),
	LEVEL8             VARCHAR2(40),
	PAID_RELEASE       DATE,
	PROJECTED_RELEASE  DATE,
	RESTRICTIONUNTIL   DATE,
	SENT_TOTAL         NUMBER(20,2),
	HOLD_TOTAL         NUMBER(20,2),
	BAIL_TOTAL         NUMBER(20,2),
	VEHICLE_ID         VARCHAR2(16),
	TOW_COMPANY        VARCHAR2(64),
	MUGPATH            VARCHAR2(4000))
	PCTFREE 10 INITRANS 1 MAXTRANS 255
	STORAGE (INITIAL 65536 MINEXTENTS 1 MAXEXTENTS 2147483645 BUFFER_POOL DEFAULT)
	TABLESPACE MACOMB;

ALTER TABLE MT_JIL_INMATE ADD (
	CONSTRAINT INMATE_PK PRIMARY KEY (ENTITY_ID_PK)
		USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
		STORAGE (INITIAL 65536 MINEXTENTS 1 MAXEXTENTS 2147483645 BUFFER_POOL DEFAULT)
		TABLESPACE MACOMB);


REM Note that this DDL is not guaranteed to include
REM   all properties of the original object.  It will also
REM   not include CLUSTER or PARTITION information.  Please
REM   report any other problems to support@benthicsoftware.com
CREATE TABLE MT_JIL_SYNC_LIST (
	JIL_SYNC_ID     VARCHAR2(16) NOT NULL,
	OFFENDER_ID     VARCHAR2(64) NOT NULL,
	ENTITY_ID       VARCHAR2(16) NOT NULL,
	BOOKING_ID      VARCHAR2(16) NOT NULL,
	ALERT_TYPE      VARCHAR2(64) NOT NULL,
	PROCESS_STATUS  VARCHAR2(2),
	COMPLETE        VARCHAR2(2),
	DATETIME        TIMESTAMP(6))
	PCTFREE 10 INITRANS 1 MAXTRANS 255
	STORAGE (INITIAL 65536 MINEXTENTS 1 MAXEXTENTS 2147483645 BUFFER_POOL DEFAULT)
	TABLESPACE MACOMB;

ALTER TABLE MT_JIL_SYNC_LIST ADD (
	PRIMARY KEY (JIL_SYNC_ID)
		USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
		STORAGE (INITIAL 65536 MINEXTENTS 1 MAXEXTENTS 2147483645 BUFFER_POOL DEFAULT)
		TABLESPACE MACOMB);


REM Note that this DDL is not guaranteed to include
REM   all properties of the original object.  It will also
REM   not include CLUSTER or PARTITION information.  Please
REM   report any other problems to support@benthicsoftware.com
CREATE TABLE MT_JIL_VISITOR (
	ENTITY_ID_FK          VARCHAR2(16) NOT NULL,
	OFFENDER_ID           VARCHAR2(64) NOT NULL,
	ENTITY_RELATED_TO_PK  VARCHAR2(16) NOT NULL,
	APPLICATION_DATE      DATE,
	EXPIRATION_DATE       DATE,
	LASTNAME              VARCHAR2(32),
	FIRSTNAME             VARCHAR2(32),
	STATUS                VARCHAR2(1),
	TYPESEQ               VARCHAR2(1))
	PCTFREE 10 INITRANS 1 MAXTRANS 255
	STORAGE (INITIAL 65536 MINEXTENTS 1 MAXEXTENTS 2147483645 BUFFER_POOL DEFAULT)
	TABLESPACE MACOMB;

ALTER TABLE MT_JIL_VISITOR ADD (
	CONSTRAINT VISITOR_PK PRIMARY KEY (ENTITY_ID_FK, ENTITY_RELATED_TO_PK)
		USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
		STORAGE (INITIAL 65536 MINEXTENTS 1 MAXEXTENTS 2147483645 BUFFER_POOL DEFAULT)
		TABLESPACE MACOMB,
	CONSTRAINT FK_VISITOR_ID FOREIGN KEY (ENTITY_ID_FK) REFERENCES MT_JIL_INMATE (ENTITY_ID_PK));


REM Note that this DDL is not guaranteed to include
REM   all properties of the original object.  It will also
REM   not include CLUSTER or PARTITION information.  Please
REM   report any other problems to support@benthicsoftware.com
CREATE TABLE MT_MG_IMAGE_DETAILS (
	IMAGE_ID         VARCHAR2(16) NOT NULL,
	ENTITY_ID        VARCHAR2(16),
	OFFENDER_ID      VARCHAR2(64),
	PURPOSE          VARCHAR2(255),
	RACE             VARCHAR2(64),
	ETHNICITY        VARCHAR2(64),
	BUILD            VARCHAR2(64),
	SKIN_TONE        VARCHAR2(64),
	LEFT_EYE_COLOR   VARCHAR2(64),
	RIGHT_EYE_COLOR  VARCHAR2(64),
	HEIGHT           NUMBER(4),
	WEIGHT           NUMBER(4),
	JUVENILE         CHAR(1),
	DOB              VARCHAR2(20),
	HAIRCOLOR        VARCHAR2(64),
	HAIRTYPE         VARCHAR2(64),
	FACIAL_HAIR1     VARCHAR2(64),
	FACIAL_HAIR2     VARCHAR2(64),
	FACIAL_HAIR3     VARCHAR2(64),
	GANG             VARCHAR2(64),
	IMAGEREF         VARCHAR2(16),
	IMAGE_TYPE       VARCHAR2(16),
	PHOTO_ID         VARCHAR2(16),
	SYSTEM           CHAR(1),
	ACTION_TYPE      CHAR(1),
	ACTION_TIME      VARCHAR2(20) NOT NULL,
	ACTION_BY        NUMBER(9) NOT NULL)
	PCTFREE 10 INITRANS 1 MAXTRANS 255
	STORAGE (INITIAL 65536 MINEXTENTS 1 MAXEXTENTS 2147483645 BUFFER_POOL DEFAULT)
	TABLESPACE MACOMB;

ALTER TABLE MT_MG_IMAGE_DETAILS ADD (
	PRIMARY KEY (IMAGE_ID)
		USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
		STORAGE (INITIAL 65536 MINEXTENTS 1 MAXEXTENTS 2147483645 BUFFER_POOL DEFAULT)
		TABLESPACE MACOMB);


REM Note that this DDL is not guaranteed to include
REM   all properties of the original object.  It will also
REM   not include CLUSTER or PARTITION information.  Please
REM   report any other problems to support@benthicsoftware.com
CREATE TABLE MT_MG_LINEUP (
	LINEUP_ID         VARCHAR2(16) NOT NULL,
	CASE_NUMBER       VARCHAR2(250) NOT NULL,
	CASE_DESCRIPTION  VARCHAR2(250),
	HEADER            VARCHAR2(250),
	FOOTER            VARCHAR2(250),
	NOTES_TEXT        VARCHAR2(1000),
	RACE              VARCHAR2(64),
	ETHNICITY         VARCHAR2(64),
	BUILD             VARCHAR2(64),
	SKIN_TONE         VARCHAR2(64),
	LEFT_EYE_COLOR    VARCHAR2(64),
	RIGHT_EYE_COLOR   VARCHAR2(64),
	HEIGHT            NUMBER(4),
	WEIGHT            NUMBER(4),
	JUVENILE          CHAR(1),
	DOB               VARCHAR2(20),
	HAIRCOLOR         VARCHAR2(64),
	HAIRTYPE          VARCHAR2(64),
	FACIAL_HAIR1      VARCHAR2(64),
	FACIAL_HAIR2      VARCHAR2(64),
	FACIAL_HAIR3      VARCHAR2(64),
	GANG              VARCHAR2(64),
	ACTION_TYPE       CHAR(1),
	ACTION_TIME       VARCHAR2(20) NOT NULL,
	ACTION_BY         NUMBER(9) NOT NULL)
	PCTFREE 10 INITRANS 1 MAXTRANS 255
	STORAGE (INITIAL 65536 MINEXTENTS 1 MAXEXTENTS 2147483645 BUFFER_POOL DEFAULT)
	TABLESPACE MACOMB;

ALTER TABLE MT_MG_LINEUP ADD (
	PRIMARY KEY (LINEUP_ID)
		USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
		STORAGE (INITIAL 65536 MINEXTENTS 1 MAXEXTENTS 2147483645 BUFFER_POOL DEFAULT)
		TABLESPACE MACOMB);


REM Note that this DDL is not guaranteed to include
REM   all properties of the original object.  It will also
REM   not include CLUSTER or PARTITION information.  Please
REM   report any other problems to support@benthicsoftware.com
CREATE TABLE MT_MG_LINEUP_PEOPLE (
	LINEUPPEOPLE_ID  VARCHAR2(16) NOT NULL,
	LINEUP_TYPE      VARCHAR2(16) NOT NULL,
	LINEUP_ID        VARCHAR2(16) NOT NULL,
	IMAGE_ID         VARCHAR2(16) NOT NULL,
	LINEUP_ROW       NUMBER(9),
	LINEUP_COL       NUMBER(9),
	HOT_SEAT         VARCHAR2(16) NOT NULL,
	ACTION_TYPE      CHAR(1),
	ACTION_TIME      VARCHAR2(20) NOT NULL,
	ACTION_BY        NUMBER(9) NOT NULL)
	PCTFREE 10 INITRANS 1 MAXTRANS 255
	STORAGE (INITIAL 65536 MINEXTENTS 1 MAXEXTENTS 2147483645 BUFFER_POOL DEFAULT)
	TABLESPACE MACOMB;

ALTER TABLE MT_MG_LINEUP_PEOPLE ADD (
	PRIMARY KEY (LINEUPPEOPLE_ID)
		USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
		STORAGE (INITIAL 65536 MINEXTENTS 1 MAXEXTENTS 2147483645 BUFFER_POOL DEFAULT)
		TABLESPACE MACOMB);


REM Note that this DDL is not guaranteed to include
REM   all properties of the original object.  It will also
REM   not include CLUSTER or PARTITION information.  Please
REM   report any other problems to support@benthicsoftware.com
CREATE TABLE MT_MG_PRESS_RELEASE (
	RELEASE_ID       VARCHAR2(16) NOT NULL,
	ENTITY_ID        VARCHAR2(16),
	OFFENDER_NUMBER  VARCHAR2(32) NOT NULL,
	RACE             VARCHAR2(64),
	ETHNICITY        VARCHAR2(64),
	BUILD            VARCHAR2(64),
	SKIN_TONE        VARCHAR2(64),
	LEFT_EYE_COLOR   VARCHAR2(64),
	RIGHT_EYE_COLOR  VARCHAR2(64),
	HEIGHT           NUMBER(4),
	WEIGHT           NUMBER(4),
	JUVENILE         CHAR(1),
	DOB              VARCHAR2(20),
	HAIRCOLOR        VARCHAR2(64),
	HAIRTYPE         VARCHAR2(64),
	FACIAL_HAIR1     VARCHAR2(64),
	FACIAL_HAIR2     VARCHAR2(64),
	FACIAL_HAIR3     VARCHAR2(64),
	GANG             VARCHAR2(64),
	TEXT_ON_CARD     VARCHAR2(500) NOT NULL,
	ACTION_TYPE      CHAR(1),
	ACTION_TIME      VARCHAR2(20) NOT NULL,
	ACTION_BY        NUMBER(9) NOT NULL)
	PCTFREE 10 INITRANS 1 MAXTRANS 255
	STORAGE (INITIAL 65536 MINEXTENTS 1 MAXEXTENTS 2147483645 BUFFER_POOL DEFAULT)
	TABLESPACE MACOMB;

ALTER TABLE MT_MG_PRESS_RELEASE ADD (
	PRIMARY KEY (RELEASE_ID)
		USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
		STORAGE (INITIAL 65536 MINEXTENTS 1 MAXEXTENTS 2147483645 BUFFER_POOL DEFAULT)
		TABLESPACE MACOMB);


REM Note that this DDL is not guaranteed to include
REM   all properties of the original object.  It will also
REM   not include CLUSTER or PARTITION information.  Please
REM   report any other problems to support@benthicsoftware.com
CREATE TABLE MT_MG_WANTED (
	WANTED_ID        VARCHAR2(16) NOT NULL,
	ENTITY_ID        VARCHAR2(16),
	OFFENDER_NUMBER  VARCHAR2(32) NOT NULL,
	TEXT_ON_POSTER   VARCHAR2(500) NOT NULL,
	ACTION_TYPE      CHAR(1),
	ACTION_TIME      VARCHAR2(20) NOT NULL,
	ACTION_BY        NUMBER(9) NOT NULL)
	PCTFREE 10 INITRANS 1 MAXTRANS 255
	STORAGE (INITIAL 65536 MINEXTENTS 1 MAXEXTENTS 2147483645 BUFFER_POOL DEFAULT)
	TABLESPACE MACOMB;

ALTER TABLE MT_MG_WANTED ADD (
	PRIMARY KEY (WANTED_ID)
		USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
		STORAGE (INITIAL 65536 MINEXTENTS 1 MAXEXTENTS 2147483645 BUFFER_POOL DEFAULT)
		TABLESPACE MACOMB);


REM Note that this DDL is not guaranteed to include
REM   all properties of the original object.  It will also
REM   not include CLUSTER or PARTITION information.  Please
REM   report any other problems to support@benthicsoftware.com
CREATE TABLE MT_PB_ARRESTEE (
	ARREST_ID                  VARCHAR2(16) NOT NULL,
	ARRIVE_TIME                DATE NOT NULL,
	ACTION_TIME                DATE,
	LASTNAME                   VARCHAR2(32) NOT NULL,
	MIDDLENAME                 VARCHAR2(64),
	FIRSTNAME                  VARCHAR2(32) NOT NULL,
	NAME_SUFFIX                VARCHAR2(64),
	NAME_TITLE                 VARCHAR2(10),
	MAIDENNAME                 VARCHAR2(32),
	OFFENDER_ID                VARCHAR2(64),
	STATE_ID                   VARCHAR2(64),
	FBI_ID                     VARCHAR2(64),
	SSN                        VARCHAR2(11),
	ACTION_BY                  VARCHAR2(16) NOT NULL,
	MATCHEDOFFENDER_ID         VARCHAR2(16),
	MUG_ID                     VARCHAR2(16),
	PRINT_ID                   VARCHAR2(16),
	TEMPHOUSINGLOCATION        VARCHAR2(64),
	RS_ADDRESS_ID              VARCHAR2(16),
	RS_DWELLING_NAME           VARCHAR2(40),
	RS_FLAT_NO_OR_FLOOR_LEVEL  VARCHAR2(8),
	RS_STREET_NUMBER           VARCHAR2(20),
	RS_STREET_NAME             VARCHAR2(40),
	RS_CITY_TOWN_LOCALE        VARCHAR2(40),
	RS_STATE_PROVINCE_REGION   VARCHAR2(64),
	RS_POSTAL_CODE             VARCHAR2(64),
	RS_CODE_COUNTRY            VARCHAR2(64),
	RS_PHONE_ID                VARCHAR2(16),
	RS_PHONE_COUNTRY_CODE      VARCHAR2(16),
	RS_PHONE_AREA_CODE         CHAR(3),
	RS_PHONE_NUMBER            VARCHAR2(10),
	RS_PHONE_EXTENSION         VARCHAR2(64),
	RS_PHONE_TYPE              VARCHAR2(64),
	CL_PHONE_ID                VARCHAR2(16),
	CL_PHONE_COUNTRY_CODE      VARCHAR2(16),
	CL_PHONE_AREA_CODE         CHAR(3),
	CL_PHONE_NUMBER            VARCHAR2(10),
	CL_PHONE_EXTENSION         VARCHAR2(64),
	CL_PHONE_TYPE              VARCHAR2(64),
	DOB                        DATE,
	HEIGHT                     VARCHAR2(64),
	WEIGHT                     VARCHAR2(64),
	RACE                       VARCHAR2(64),
	GENDER                     VARCHAR2(64),
	EYERIGHT                   VARCHAR2(64),
	EYELEFT                    VARCHAR2(64),
	HAIR                       VARCHAR2(64),
	COMPLEXION                 VARCHAR2(64),
	MARITALSTATUS              VARCHAR2(64),
	BIRTHCITY                  VARCHAR2(40),
	BIRTHSTATE                 VARCHAR2(64),
	BIRTHCOUNTRY               VARCHAR2(64),
	RELIGIOUSPREF              VARCHAR2(64),
	DL_ID                      VARCHAR2(16),
	DLNUMBER                   VARCHAR2(64),
	DLSTATE                    VARCHAR2(64),
	DLEXPIRE                   DATE,
	ENGLISHSPOKEN              VARCHAR2(64),
	ENGLISHREAD                VARCHAR2(64),
	ENGLISHWRITTEN             VARCHAR2(64),
	EDUCATIONLEVEL             VARCHAR2(64),
	EMPLOYEMENT_ID             VARCHAR2(16),
	OCCUPATION                 VARCHAR2(64),
	EMPLOYERNAME               VARCHAR2(64),
	EM_ADDRESS_ID              VARCHAR2(16),
	EM_DWELLING_NAME           VARCHAR2(40),
	EM_FLAT_NO_OR_FLOOR_LEVEL  VARCHAR2(8),
	EM_STREET_NUMBER           VARCHAR2(20),
	EM_STREET_NAME             VARCHAR2(40),
	EM_CITY_TOWN_LOCALE        VARCHAR2(40),
	EM_STATE_PROVINCE_REGION   VARCHAR2(64),
	EM_POSTAL_CODE             VARCHAR2(64),
	EM_PHONE_ID                VARCHAR2(16),
	EM_CODE_COUNTRY            VARCHAR2(64),
	EM_PHONE_COUNTRY_CODE      VARCHAR2(16),
	EM_PHONE_AREA_CODE         CHAR(3),
	EM_PHONE_NUMBER            VARCHAR2(10),
	EM_PHONE_EXTENSION         VARCHAR2(64),
	EM_PHONE_TYPE              VARCHAR2(64),
	EC_PERSON_ID               VARCHAR2(16),
	EMERGENCYCONTACT           VARCHAR2(64),
	EC_PHONE_ID                VARCHAR2(16),
	EC_PHONE_COUNTRY_CODE      VARCHAR2(16),
	EC_PHONE_AREA_CODE         CHAR(3),
	EC_PHONE_NUMBER            VARCHAR2(10),
	EC_PHONE_EXTENSION         VARCHAR2(64),
	EC_PHONE_TYPE              VARCHAR2(64),
	EMERGENCYRELATIONSHIP      VARCHAR2(64),
	ASSULTIVEFLAG              CHAR(1),
	MEDICALFLAG                CHAR(1),
	SUICIDEFLAG                CHAR(1),
	SPRAYFLAG                  CHAR(1),
	SPRAYWHEN                  DATE,
	ELECTROSHOCKFLAG           CHAR(1),
	ELECTROSHOCKWHEN           DATE,
	CAUTIONCOMMENT             VARCHAR2(255),
	HOMELESS                   CHAR(1),
	USCITIZEN                  CHAR(1))
	PCTFREE 10 INITRANS 1 MAXTRANS 255
	STORAGE (INITIAL 65536 MINEXTENTS 1 MAXEXTENTS 2147483645 BUFFER_POOL DEFAULT)
	TABLESPACE MACOMB;

ALTER TABLE MT_PB_ARRESTEE ADD (
	PRIMARY KEY (ARREST_ID)
		USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
		STORAGE (INITIAL 65536 MINEXTENTS 1 MAXEXTENTS 2147483645 BUFFER_POOL DEFAULT)
		TABLESPACE MACOMB,
	CONSTRAINT MATCHEDOFFENDER_ID_UNIQUE UNIQUE (MATCHEDOFFENDER_ID, ARREST_ID)
		USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
		STORAGE (INITIAL 65536 MINEXTENTS 1 MAXEXTENTS 2147483645 BUFFER_POOL DEFAULT)
		TABLESPACE MACOMB);


REM Note that this DDL is not guaranteed to include
REM   all properties of the original object.  It will also
REM   not include CLUSTER or PARTITION information.  Please
REM   report any other problems to support@benthicsoftware.com
CREATE TABLE MT_PB_ARREST_CHARGE (
	ARREST_ID        VARCHAR2(16) NOT NULL,
	CHARGE_ID        VARCHAR2(16) NOT NULL,
	CHARGE           VARCHAR2(64) NOT NULL,
	PACC             VARCHAR2(64) NOT NULL,
	INCIDENTNUMBER   VARCHAR2(64) NOT NULL,
	CRIMEYEAR        VARCHAR2(4),
	COUNT            NUMBER(2),
	CLASS            VARCHAR2(64),
	ARRESTREASON     VARCHAR2(64) NOT NULL,
	COURTNAME        VARCHAR2(64),
	COMPLAINTAGENCY  VARCHAR2(64) NOT NULL,
	ARRESTAGENCY     VARCHAR2(64) NOT NULL,
	TCN              VARCHAR2(16),
	CTN              VARCHAR2(16),
	STATUTE_ID       VARCHAR2(16))
	PCTFREE 10 INITRANS 1 MAXTRANS 255
	STORAGE (INITIAL 65536 MINEXTENTS 1 MAXEXTENTS 2147483645 BUFFER_POOL DEFAULT)
	TABLESPACE MACOMB;

ALTER TABLE MT_PB_ARREST_CHARGE ADD (
	PRIMARY KEY (CHARGE_ID)
		USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
		STORAGE (INITIAL 65536 MINEXTENTS 1 MAXEXTENTS 2147483645 BUFFER_POOL DEFAULT)
		TABLESPACE MACOMB);


REM Note that this DDL is not guaranteed to include
REM   all properties of the original object.  It will also
REM   not include CLUSTER or PARTITION information.  Please
REM   report any other problems to support@benthicsoftware.com
CREATE TABLE MT_PB_ARREST_DETAIL (
	ARREST_ID        VARCHAR2(16) NOT NULL,
	ARRESTDATE       VARCHAR2(10),
	ARRESTTIME       VARCHAR2(8),
	ARRESTEDWITH_ID  VARCHAR2(16),
	ARRESTLOCATION   VARCHAR2(64),
	ARRESTCITY       VARCHAR2(40),
	ARRESTSTATE      VARCHAR2(64),
	ARRESTPREVHELD   VARCHAR2(64),
	VEHICLETOWEDTO   VARCHAR2(16),
	ARRESTDATETIME   DATE)
	PCTFREE 10 INITRANS 1 MAXTRANS 255
	STORAGE (INITIAL 65536 MINEXTENTS 1 MAXEXTENTS 2147483645 BUFFER_POOL DEFAULT)
	TABLESPACE MACOMB;

ALTER TABLE MT_PB_ARREST_DETAIL ADD (
	PRIMARY KEY (ARREST_ID)
		USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
		STORAGE (INITIAL 65536 MINEXTENTS 1 MAXEXTENTS 2147483645 BUFFER_POOL DEFAULT)
		TABLESPACE MACOMB);


REM Note that this DDL is not guaranteed to include
REM   all properties of the original object.  It will also
REM   not include CLUSTER or PARTITION information.  Please
REM   report any other problems to support@benthicsoftware.com
CREATE TABLE MT_PB_ARREST_OFFICER (
	ARRESTOFFICER_PK   VARCHAR2(35) NOT NULL,
	ARREST_ID          VARCHAR2(16) NOT NULL,
	OFFICERDEPARTMENT  VARCHAR2(64),
	OFFICERROLE        VARCHAR2(64),
	OFFICERNAME        VARCHAR2(64),
	OFFICERBADGE       VARCHAR2(64))
	PCTFREE 10 INITRANS 1 MAXTRANS 255
	STORAGE (INITIAL 65536 MINEXTENTS 1 MAXEXTENTS 2147483645 BUFFER_POOL DEFAULT)
	TABLESPACE MACOMB;

ALTER TABLE MT_PB_ARREST_OFFICER ADD (
	PRIMARY KEY (ARRESTOFFICER_PK)
		USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
		STORAGE (INITIAL 65536 MINEXTENTS 1 MAXEXTENTS 2147483645 BUFFER_POOL DEFAULT)
		TABLESPACE MACOMB);


REM Note that this DDL is not guaranteed to include
REM   all properties of the original object.  It will also
REM   not include CLUSTER or PARTITION information.  Please
REM   report any other problems to support@benthicsoftware.com
CREATE TABLE MT_PB_ARREST_PROPERTY (
	ARREST_ID    VARCHAR2(16) NOT NULL,
	PROPERTY_ID  VARCHAR2(16) NOT NULL,
	PROPERTY     VARCHAR2(255) NOT NULL,
	DESCRIPTION  VARCHAR2(64) NOT NULL,
	IMAGE        VARCHAR2(255),
	QUANTITY     NUMBER(6),
	COLOR        VARCHAR2(64))
	PCTFREE 10 INITRANS 1 MAXTRANS 255
	STORAGE (INITIAL 65536 MINEXTENTS 1 MAXEXTENTS 2147483645 BUFFER_POOL DEFAULT)
	TABLESPACE MACOMB;

ALTER TABLE MT_PB_ARREST_PROPERTY ADD (
	PRIMARY KEY (PROPERTY_ID)
		USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
		STORAGE (INITIAL 65536 MINEXTENTS 1 MAXEXTENTS 2147483645 BUFFER_POOL DEFAULT)
		TABLESPACE MACOMB);


REM Note that this DDL is not guaranteed to include
REM   all properties of the original object.  It will also
REM   not include CLUSTER or PARTITION information.  Please
REM   report any other problems to support@benthicsoftware.com
CREATE TABLE MT_PB_BIOMETERIC (
	BIOMETERIC_ID    VARCHAR2(16) NOT NULL,
	ARREST_ID        VARCHAR2(16) NOT NULL,
	BIOTYPE_ID       VARCHAR2(16) NOT NULL,
	BIODESCRIPTION   VARCHAR2(64) NOT NULL,
	BIOVOLUMESERVER  VARCHAR2(255) NOT NULL,
	BIOVOLUMEPATH    VARCHAR2(255) NOT NULL,
	BIOIMAGEREF      VARCHAR2(16) NOT NULL)
	PCTFREE 10 INITRANS 1 MAXTRANS 255
	STORAGE (INITIAL 65536 MINEXTENTS 1 MAXEXTENTS 2147483645 BUFFER_POOL DEFAULT)
	TABLESPACE MACOMB;

ALTER TABLE MT_PB_BIOMETERIC ADD (
	PRIMARY KEY (BIOMETERIC_ID)
		USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
		STORAGE (INITIAL 65536 MINEXTENTS 1 MAXEXTENTS 2147483645 BUFFER_POOL DEFAULT)
		TABLESPACE MACOMB);


REM Note that this DDL is not guaranteed to include
REM   all properties of the original object.  It will also
REM   not include CLUSTER or PARTITION information.  Please
REM   report any other problems to support@benthicsoftware.com
CREATE TABLE MT_PB_BIOTYPE (
	BIOTYPE_ID      VARCHAR2(16) NOT NULL,
	BIODESCRIPTION  VARCHAR2(64) NOT NULL)
	PCTFREE 10 INITRANS 1 MAXTRANS 255
	STORAGE (INITIAL 65536 MINEXTENTS 1 MAXEXTENTS 2147483645 BUFFER_POOL DEFAULT)
	TABLESPACE MACOMB;

ALTER TABLE MT_PB_BIOTYPE ADD (
	PRIMARY KEY (BIOTYPE_ID)
		USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
		STORAGE (INITIAL 65536 MINEXTENTS 1 MAXEXTENTS 2147483645 BUFFER_POOL DEFAULT)
		TABLESPACE MACOMB);


REM Note that this DDL is not guaranteed to include
REM   all properties of the original object.  It will also
REM   not include CLUSTER or PARTITION information.  Please
REM   report any other problems to support@benthicsoftware.com
CREATE TABLE MT_PB_DEPT (
	DEPARTMENT_ID    VARCHAR2(16) NOT NULL,
	DEPARTMENTNAME   VARCHAR2(64) NOT NULL,
	DEPARTMENTCITY   VARCHAR2(40) NOT NULL,
	DEPARTMENTSTATE  VARCHAR2(64) NOT NULL,
	DEPARTNEMTZIP    VARCHAR2(64) NOT NULL)
	PCTFREE 10 INITRANS 1 MAXTRANS 255
	STORAGE (INITIAL 65536 MINEXTENTS 1 MAXEXTENTS 2147483645 BUFFER_POOL DEFAULT)
	TABLESPACE MACOMB;

ALTER TABLE MT_PB_DEPT ADD (
	PRIMARY KEY (DEPARTMENT_ID)
		USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
		STORAGE (INITIAL 65536 MINEXTENTS 1 MAXEXTENTS 2147483645 BUFFER_POOL DEFAULT)
		TABLESPACE MACOMB);


REM Note that this DDL is not guaranteed to include
REM   all properties of the original object.  It will also
REM   not include CLUSTER or PARTITION information.  Please
REM   report any other problems to support@benthicsoftware.com
CREATE TABLE MT_PB_KEEP_SEPARATE (
	KEEP_SEPARATE_ID    VARCHAR2(16) NOT NULL,
	ORIGIN_ENTITY_ID    VARCHAR2(16) NOT NULL,
	SEPARATE_ENTITY_ID  VARCHAR2(16) NOT NULL,
	LOCATION_ID         VARCHAR2(64) NOT NULL)
	PCTFREE 10 INITRANS 1 MAXTRANS 255
	STORAGE (INITIAL 65536 MINEXTENTS 1 MAXEXTENTS 2147483645 BUFFER_POOL DEFAULT)
	TABLESPACE MACOMB;

ALTER TABLE MT_PB_KEEP_SEPARATE ADD (
	PRIMARY KEY (KEEP_SEPARATE_ID)
		USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
		STORAGE (INITIAL 65536 MINEXTENTS 1 MAXEXTENTS 2147483645 BUFFER_POOL DEFAULT)
		TABLESPACE MACOMB);


REM Note that this DDL is not guaranteed to include
REM   all properties of the original object.  It will also
REM   not include CLUSTER or PARTITION information.  Please
REM   report any other problems to support@benthicsoftware.com
CREATE TABLE MT_PB_LANGUAGE (
	LANGUAGE_ID   VARCHAR2(16) NOT NULL,
	ARREST_ID     VARCHAR2(16) NOT NULL,
	LANGUAGETYPE  VARCHAR2(64) NOT NULL)
	PCTFREE 10 INITRANS 1 MAXTRANS 255
	STORAGE (INITIAL 65536 MINEXTENTS 1 MAXEXTENTS 2147483645 BUFFER_POOL DEFAULT)
	TABLESPACE MACOMB;

ALTER TABLE MT_PB_LANGUAGE ADD (
	PRIMARY KEY (LANGUAGE_ID)
		USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
		STORAGE (INITIAL 65536 MINEXTENTS 1 MAXEXTENTS 2147483645 BUFFER_POOL DEFAULT)
		TABLESPACE MACOMB);


REM Note that this DDL is not guaranteed to include
REM   all properties of the original object.  It will also
REM   not include CLUSTER or PARTITION information.  Please
REM   report any other problems to support@benthicsoftware.com
CREATE TABLE MT_PB_OFFICERS (
	OFFICER_ID         VARCHAR2(16) NOT NULL,
	ARREST_ID          VARCHAR2(16) NOT NULL,
	OFFICERDEPARTMENT  VARCHAR2(16),
	OFFICERROLE        VARCHAR2(64),
	OFFICERNAME        VARCHAR2(64),
	OFFICERBADGE       VARCHAR2(64))
	PCTFREE 10 INITRANS 1 MAXTRANS 255
	STORAGE (INITIAL 65536 MINEXTENTS 1 MAXEXTENTS 2147483645 BUFFER_POOL DEFAULT)
	TABLESPACE MACOMB;

ALTER TABLE MT_PB_OFFICERS ADD (
	PRIMARY KEY (OFFICER_ID)
		USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
		STORAGE (INITIAL 65536 MINEXTENTS 1 MAXEXTENTS 2147483645 BUFFER_POOL DEFAULT)
		TABLESPACE MACOMB);


REM Note that this DDL is not guaranteed to include
REM   all properties of the original object.  It will also
REM   not include CLUSTER or PARTITION information.  Please
REM   report any other problems to support@benthicsoftware.com
CREATE TABLE MT_PB_PERSON_ALIAS (
	ALIAS_ID   VARCHAR2(16) NOT NULL,
	ARREST_ID  VARCHAR2(16) NOT NULL,
	FIRSTNAME  VARCHAR2(32) NOT NULL,
	LASTNAME   VARCHAR2(32) NOT NULL,
	NAMETYPE   VARCHAR2(64) NOT NULL,
	OT_DATA    VARCHAR2(1),
	DOB        DATE,
	SSN        VARCHAR2(11))
	PCTFREE 10 INITRANS 1 MAXTRANS 255
	STORAGE (INITIAL 65536 MINEXTENTS 1 MAXEXTENTS 2147483645 BUFFER_POOL DEFAULT)
	TABLESPACE MACOMB;

ALTER TABLE MT_PB_PERSON_ALIAS ADD (
	PRIMARY KEY (ALIAS_ID)
		USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
		STORAGE (INITIAL 65536 MINEXTENTS 1 MAXEXTENTS 2147483645 BUFFER_POOL DEFAULT)
		TABLESPACE MACOMB,
	CONSTRAINT MT_PB_PERSON__UK21155568957504 UNIQUE (ALIAS_ID, ARREST_ID)
		USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
		STORAGE (INITIAL 65536 MINEXTENTS 1 MAXEXTENTS 2147483645 BUFFER_POOL DEFAULT)
		TABLESPACE MACOMB);


REM Note that this DDL is not guaranteed to include
REM   all properties of the original object.  It will also
REM   not include CLUSTER or PARTITION information.  Please
REM   report any other problems to support@benthicsoftware.com
CREATE TABLE MT_PB_PROPERTY_COLOR (
	COLORID          VARCHAR2(16) NOT NULL,
	DESCRIPTION      VARCHAR2(64) NOT NULL,
	SORTORDER        NUMBER,
	CODE_ITEM_COLOR  VARCHAR2(64))
	PCTFREE 10 INITRANS 1 MAXTRANS 255
	STORAGE (INITIAL 65536 MINEXTENTS 1 MAXEXTENTS 2147483645 BUFFER_POOL DEFAULT)
	TABLESPACE MACOMB;

ALTER TABLE MT_PB_PROPERTY_COLOR ADD (
	CONSTRAINT COLOR_PK PRIMARY KEY (COLORID)
		USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
		STORAGE (INITIAL 65536 MINEXTENTS 1 MAXEXTENTS 2147483645 BUFFER_POOL DEFAULT)
		TABLESPACE MACOMB);


REM Note that this DDL is not guaranteed to include
REM   all properties of the original object.  It will also
REM   not include CLUSTER or PARTITION information.  Please
REM   report any other problems to support@benthicsoftware.com
CREATE TABLE MT_PB_PROPERTY_COND (
	CONDID               VARCHAR2(16) NOT NULL,
	DESCRIPTION          VARCHAR2(64) NOT NULL,
	SORTORDER            NUMBER,
	CODE_ITEM_CONDITION  VARCHAR2(64));

ALTER TABLE MT_PB_PROPERTY_COND ADD (
	CONSTRAINT COND_PK PRIMARY KEY (CONDID));


REM Note that this DDL is not guaranteed to include
REM   all properties of the original object.  It will also
REM   not include CLUSTER or PARTITION information.  Please
REM   report any other problems to support@benthicsoftware.com
CREATE TABLE MT_PB_PROPERTY_LK (
	PROPERTY_ID  VARCHAR2(16) NOT NULL,
	DESCRIPTION  VARCHAR2(64) NOT NULL,
	SORTORDER    VARCHAR2(2),
	ITEM_NAME    VARCHAR2(64));

ALTER TABLE MT_PB_PROPERTY_LK ADD (
	PRIMARY KEY (PROPERTY_ID));


REM Note that this DDL is not guaranteed to include
REM   all properties of the original object.  It will also
REM   not include CLUSTER or PARTITION information.  Please
REM   report any other problems to support@benthicsoftware.com
CREATE TABLE MT_PB_STEP_LK (
	STEP_ID          VARCHAR2(16) NOT NULL,
	STEPDESCRIPTION  VARCHAR2(64) NOT NULL);

ALTER TABLE MT_PB_STEP_LK ADD (
	PRIMARY KEY (STEP_ID));


REM Note that this DDL is not guaranteed to include
REM   all properties of the original object.  It will also
REM   not include CLUSTER or PARTITION information.  Please
REM   report any other problems to support@benthicsoftware.com
CREATE TABLE MT_PB_TEMP_HOUSING (
	HOUSING_ID  VARCHAR2(16) NOT NULL,
	CELL_NAME   VARCHAR2(4) NOT NULL,
	GENDER      CHAR(1) NOT NULL);

ALTER TABLE MT_PB_TEMP_HOUSING ADD (
	PRIMARY KEY (HOUSING_ID));


REM Note that this DDL is not guaranteed to include
REM   all properties of the original object.  It will also
REM   not include CLUSTER or PARTITION information.  Please
REM   report any other problems to support@benthicsoftware.com
CREATE TABLE MT_PB_TIMING (
	TIMING_ID  VARCHAR2(16) NOT NULL,
	ARREST_ID  VARCHAR2(16) NOT NULL,
	ACTION_BY  VARCHAR2(16) NOT NULL,
	STEP_ID    VARCHAR2(64) NOT NULL,
	DURATION   NUMBER(12,4));

ALTER TABLE MT_PB_TIMING ADD (
	PRIMARY KEY (TIMING_ID));


REM Note that this DDL is not guaranteed to include
REM   all properties of the original object.  It will also
REM   not include CLUSTER or PARTITION information.  Please
REM   report any other problems to support@benthicsoftware.com
CREATE TABLE MT_PB_TOW_DETAILS (
	TOWCOMANY_ID        VARCHAR2(16) NOT NULL,
	TOWCOMPANYNAME      VARCHAR2(255) NOT NULL,
	PHONE_COUNTRY_CODE  VARCHAR2(4),
	PHONE_AREA_CODE     CHAR(3),
	PHONE_NUMBER        VARCHAR2(10),
	PHONE_EXTENSION     VARCHAR2(6),
	TOWCOMPANYLOCATION  VARCHAR2(64),
	TOWCOMPANYCITY      VARCHAR2(40),
	TOWCOMPANYSTATE     VARCHAR2(64),
	TOWCOMPANYZIP       VARCHAR2(64),
	TOWCOMPANYCODE      VARCHAR2(64));

ALTER TABLE MT_PB_TOW_DETAILS ADD (
	PRIMARY KEY (TOWCOMANY_ID));


REM Note that this DDL is not guaranteed to include
REM   all properties of the original object.  It will also
REM   not include CLUSTER or PARTITION information.  Please
REM   report any other problems to support@benthicsoftware.com
CREATE TABLE MT_PB_WORKFLOW (
	TASKID    CHAR(16) NOT NULL,
	TASKNAME  VARCHAR2(64) NOT NULL,
	LGCFIELD  VARCHAR2(2000));

ALTER TABLE MT_PB_WORKFLOW ADD (
	CONSTRAINT TASK_PK PRIMARY KEY (TASKID));


REM Note that this DDL is not guaranteed to include
REM   all properties of the original object.  It will also
REM   not include CLUSTER or PARTITION information.  Please
REM   report any other problems to support@benthicsoftware.com
CREATE TABLE MT_WORKFLOW_AGING (
	AGING_ID     VARCHAR2(16),
	TASK_ID      VARCHAR2(16),
	OLDERTHAN    NUMBER(5) NOT NULL,
	NOTIFY_FLAG  VARCHAR2(20),
	EMAIL        VARCHAR2(200),
	USERID       VARCHAR2(10),
	COLOR        VARCHAR2(20) NOT NULL);

ALTER TABLE MT_WORKFLOW_AGING ADD (
	PRIMARY KEY (AGING_ID));

CREATE BITMAP INDEX MI_WORKFLOW_TASK_ID ON MT_WORKFLOW_AGING (TASK_ID, OLDERTHAN);


REM Note that this DDL is not guaranteed to include
REM   all properties of the original object.  It will also
REM   not include CLUSTER or PARTITION information.  Please
REM   report any other problems to support@benthicsoftware.com
CREATE TABLE PLAN_TABLE (
	STATEMENT_ID     VARCHAR2(30),
	TIMESTAMP        DATE,
	REMARKS          VARCHAR2(80),
	OPERATION        VARCHAR2(30),
	OPTIONS          VARCHAR2(30),
	OBJECT_NODE      VARCHAR2(128),
	OBJECT_OWNER     VARCHAR2(30),
	OBJECT_NAME      VARCHAR2(30),
	OBJECT_INSTANCE  NUMBER,
	OBJECT_TYPE      VARCHAR2(30),
	OPTIMIZER        VARCHAR2(255),
	SEARCH_COLUMNS   NUMBER,
	ID               NUMBER,
	PARENT_ID        NUMBER,
	POSITION         NUMBER,
	COST             NUMBER,
	CARDINALITY      NUMBER,
	BYTES            NUMBER,
	OTHER_TAG        VARCHAR2(255),
	PARTITION_START  VARCHAR2(255),
	PARTITION_STOP   VARCHAR2(255),
	PARTITION_ID     NUMBER,
	OTHER            LONG,
	DISTRIBUTION     VARCHAR2(30));


REM Note that this DDL is not guaranteed to include
REM   all properties of the original object.  It will also
REM   not include CLUSTER or PARTITION information.  Please
REM   report any other problems to support@benthicsoftware.com
CREATE TABLE PS_TXN (
	ID             NUMBER(20),
	PARENTID       NUMBER(20),
	COLLID         NUMBER(10),
	CONTENT        BLOB,
	CREATION_DATE  DATE DEFAULT sysdate);

ALTER TABLE PS_TXN ADD (
	CONSTRAINT PS_TXN_PK PRIMARY KEY (COLLID, ID));


REM Note that this DDL is not guaranteed to include
REM   all properties of the original object.  It will also
REM   not include CLUSTER or PARTITION information.  Please
REM   report any other problems to support@benthicsoftware.com
CREATE TABLE WEB_ALIAS (
	ENTITY_ID       VARCHAR2(16) NOT NULL,
	ALIAS_ID        VARCHAR2(16) NOT NULL,
	LASTNAME        VARCHAR2(64),
	FIRSTNAME       VARCHAR2(64),
	MIDDLENAME      VARCHAR2(64),
	SUFFIXNAME      VARCHAR2(64),
	DOB             VARCHAR2(11),
	CODE_NAME_TYPE  VARCHAR2(64));

ALTER TABLE WEB_ALIAS ADD (
	CONSTRAINT WEB_ALIAS_ID PRIMARY KEY (ALIAS_ID));


REM Note that this DDL is not guaranteed to include
REM   all properties of the original object.  It will also
REM   not include CLUSTER or PARTITION information.  Please
REM   report any other problems to support@benthicsoftware.com
CREATE TABLE WEB_CHARGE (
	ENTITY_ID              VARCHAR2(16) NOT NULL,
	CHARGE_ID              VARCHAR2(16),
	STATUTE_ID             VARCHAR2(64),
	PACC                   VARCHAR2(64),
	CHARGE_DESC            VARCHAR2(255),
	CHARGE_CLASS           VARCHAR2(64),
	SENTENCE_ID            VARCHAR2(16),
	CHARGE_ID_NUMBER       VARCHAR2(64),
	AGENCY_ID              VARCHAR2(16),
	COMPLAINT_DEPT         VARCHAR2(64),
	COURT_ID               VARCHAR2(16),
	CASE_NO                VARCHAR2(64),
	COURT_NAME             VARCHAR2(64),
	COURT_DATE             VARCHAR2(10),
	COURT_DIVISION         VARCHAR2(64),
	JUDGE                  VARCHAR2(64),
	START_DATE             DATE,
	SENTENCE_START_DATE    DATE,
	EARLIEST_RELEASE_DATE  DATE,
	FINAL_RELEASE_DATE     DATE,
	END_DATE               DATE,
	AMOUNT                 NUMBER(20,2),
	AMOUNT_TYPE            CHAR(10),
	TRANS_TYPE             CHAR(1),
	SORT_ORDER             CHAR(1),
	WEB_CHARGE_PK          VARCHAR2(64) NOT NULL,
	REDUCEAMOUNT           CHAR(1),
	PAIDOUTDATE            DATE,
	UNPAIDOUTDATE          DATE);

ALTER TABLE WEB_CHARGE ADD (
	CONSTRAINT WEB_CHARGE_PK PRIMARY KEY (WEB_CHARGE_PK));


REM Note that this DDL is not guaranteed to include
REM   all properties of the original object.  It will also
REM   not include CLUSTER or PARTITION information.  Please
REM   report any other problems to support@benthicsoftware.com
CREATE TABLE WEB_INMATE (
	ENTITY_ID         VARCHAR2(16) NOT NULL,
	LASTNAME          VARCHAR2(64),
	FIRSTNAME         VARCHAR2(64),
	LOCATION4         VARCHAR2(20),
	LOCATION5         VARCHAR2(20),
	LOCATION6         VARCHAR2(20),
	LOCATION7         VARCHAR2(20),
	LOCATION8         VARCHAR2(20),
	DOB               VARCHAR2(11),
	RELEASEDATE       DATE,
	PAIDRELEASEDATE   DATE,
	JUVENILE_FLAG     CHAR(1),
	TOTALBONDS        NUMBER(20,2),
	TOTALFINES        NUMBER(20,2),
	TOTALHOLDS        NUMBER(20,2),
	MUGLOCATION       VARCHAR2(255),
	VEHICLE_ID        VARCHAR2(16),
	TOWCOMPANYNAME    VARCHAR2(64),
	OTHERNAME         VARCHAR2(64),
	INMATECLASS       CHAR(1),
	GENDER            CHAR(1),
	CELL              VARCHAR2(10),
	RESTRICTIONUNTIL  DATE);

ALTER TABLE WEB_INMATE ADD (
	CONSTRAINT WEB_INMATE_PK PRIMARY KEY (ENTITY_ID));


REM Note that this DDL is not guaranteed to include
REM   all properties of the original object.  It will also
REM   not include CLUSTER or PARTITION information.  Please
REM   report any other problems to support@benthicsoftware.com
CREATE TABLE WEB_VISITATION (
	ENTRANCE           CHAR(1),
	DAYOFWEEK          VARCHAR2(5),
	STARTTIME          VARCHAR2(10),
	ENDTIME            VARCHAR2(10),
	VISITINGAREA       VARCHAR2(64),
	VISITATION_TYPE    VARCHAR2(10),
	GENDER             CHAR(1),
	INMATECLASS        CHAR(1),
	HOUSING5           VARCHAR2(64),
	HOUSING6           VARCHAR2(64),
	HOUSING7           VARCHAR2(64),
	WEB_VISITATION_ID  VARCHAR2(16),
	REPORT             VARCHAR2(64),
	CELL               VARCHAR2(10),
	INMATETYPE         CHAR(1));


REM Note that this DDL is not guaranteed to include
REM   all properties of the original object.  It will also
REM   not include CLUSTER or PARTITION information.  Please
REM   report any other problems to support@benthicsoftware.com
CREATE TABLE WEB_VISITATION_CELL (
	WEB_VISITATION_CELL_ID  VARCHAR2(16) NOT NULL,
	INMATETYPE              CHAR(1),
	JUVENILE                CHAR(1),
	GENDER                  CHAR(1),
	CELL                    VARCHAR2(10),
	WEB_VISITATION_ID       VARCHAR2(16));

ALTER TABLE WEB_VISITATION_CELL ADD (
	CONSTRAINT WEB_VISITATION_CELL_ID PRIMARY KEY (WEB_VISITATION_CELL_ID));


REM Note that this DDL is not guaranteed to include
REM   all properties of the original object.  It will also
REM   not include CLUSTER or PARTITION information.  Please
REM   report any other problems to support@benthicsoftware.com
CREATE TABLE WEB_VISITOR (
	ENTITY_ID         VARCHAR2(16),
	VISITOR_ID        VARCHAR2(16) NOT NULL,
	APPLICATION_DATE  VARCHAR2(11),
	EXPIRATION_DATE   VARCHAR2(11),
	LASTNAME          VARCHAR2(64),
	FIRSTNAME         VARCHAR2(64),
	STATUS            CHAR(1) NOT NULL,
	TYPESEQ           CHAR(1) NOT NULL,
	VISITOR_PK        VARCHAR2(33) NOT NULL);

ALTER TABLE WEB_VISITOR ADD (
	CONSTRAINT WEB_VISITOR_PK PRIMARY KEY (VISITOR_PK));

REM
REM
REM
REM VIEWS
REM
REM
REM

REM Note that this DDL is not guaranteed to include
REM   all properties of the original object.  It will also
REM   not include CLUSTER or PARTITION information.  Please
REM   report any other problems to support@benthicsoftware.com
CREATE OR REPLACE VIEW MCMB_VIEW_ALIAS (ENTITY_ID, ALIAS_ID, LASTNAME, FIRSTNAME, MIDDLENAME, SUFFIXNAME, DOB, CODE_NAME_TYPE, LINK_PK) AS
select 	id.OFFENDER_ID AS entity_id,
		pi.identity_id AS alias_id,
		pi.name_family AS lastname,
		pi.name_first  AS firstname,
		pi.name_other  AS middlename,
		pi.name_suffix AS suffixname,
 	    NVL(NVL(to_char(EPIC.ef_epic_date_to_date(pi.DATE_OF_BIRTH),'MM/DD/YYYY'),
 	    		to_char(EPIC.ef_epic_date_to_date(pi.BIRTH_DATE_APPROX),'MM/DD/YYYY')),
 	                   'UNKNOWN') AS DOB,
 	    pi.CODE_NAME_TYPE AS CODE_NAME_TYPE,
 	    decode(pi.CODE_NAME_TYPE, 'MAS',id.OFFENDER_ID, 'ALIAS') AS LINK_PK
FROM    EPIC.eh_person_identity pi,
		EPIC.eh_offender_ids id
WHERE	id.ENTITY_ID = pi.entity_id
  AND	pi.CODE_NAME_TYPE in ('MAS','ALI')
  AND EXISTS (select 1 from EPIC.eh_active_booking ab where id.entity_id = ab.entity_id);


REM Note that this DDL is not guaranteed to include
REM   all properties of the original object.  It will also
REM   not include CLUSTER or PARTITION information.  Please
REM   report any other problems to support@benthicsoftware.com
CREATE OR REPLACE VIEW MCMB_VIEW_CHARGE (ENTITY_ID, CHARGE_ID, STATUTE_ID, PACC, CHARGE_DESC, CHARGE_CLASS, SENTENCE_ID, CHARGE_ID_NUMBER, AGENCY_ID, COMPLAINT_DEPT, COURT_ID, CASE_NO, COURT_NAME, COURT_DATE, COURT_DIVISION, COURT_JUDGE, START_DATE, FINAL_RELEASE_DATE, AMOUNT, AMOUNT_TYPE, TRANS_TYPE, SORTORDER, WEB_CHARGE_PK, REDUCEAMOUNT, PAIDOUTDATE, UNPAIDOUTDATE) AS
SELECT 	id.OFFENDER_ID				AS entity_id,
		c.charge_id 				AS charge_id,
        c.statute_id 				AS statute_id,
        es.statute_number 			AS pacc,
        es.statute_description 		AS charge_desc,
    	EPIC.ef_lookup_text('STATUTE CLASS', es.code_statute_class, 'UC') AS charge_class,
        s.sentence_id 				AS sentence_id,
       	charge_id_number 			AS charge_id_number,
       	ca.agency_id 				AS agency_id,
       	eo.organization_name 		AS complaint_dept,
       	cct.court_id 				AS court_id,
       	cs.case_number 				AS case_no,
       	EPIC.mcmb_fnt_courtname(c.charge_id) AS court_name,
       	decode(
       	to_char(EPIC.ef_epic_date_to_date(EPIC.ef_next_court_date(b.entity_id)),'MM/DD/YYYY'),'12/25/2025','Call Court',
       	to_char(EPIC.ef_epic_date_to_date(EPIC.ef_next_court_date(b.entity_id)),'MM/DD/YYYY')) AS court_date,
       	
       	EPIC.ef_next_court_division(b.entity_id) AS court_division,
       	EPIC.ef_lookup_text('JUDGE NAME',EPIC.ef_next_court_judge(b.entity_id),'UC') AS court_judge,
		EPIC.ef_epic_date_to_date(EPIC.epp_booking_dates.start_date(b.booking_id))         		AS Start_Date,
		EPIC.ef_epic_date_to_date(EPIC.epp_booking_dates.final_release_date(b.booking_id))     	AS final_releASe_date ,
		decode(c.sentence_id,NULL,
							to_number(bc.cash_only_bail_amount),
							to_number(EPIC.mcmb_fnt_fineamount(c.sentence_id)))  AS amount,
		decode(c.sentence_id,NULL, 'BAIL', 'FINE') AS amount_type,
		decode(c.sentence_id,NULL, 'U', 'S') AS Trans_type,
		decode(c.sentence_id,NULL, 2, 1) AS sortorder,
		EPIC.ef_offender_id(b.entity_id)||' - '||c.charge_id  AS web_charge_pk,
		decode(EPIC.ef_get_attribute_value('10 PERCENT BOND',bc.BAIL_CONDITION_ID),'YES',
															'Y',
															'N') AS reduceamount,
		so.paid_out_date AS paidoutdate,
		so.unpaid_out_date AS unpaidoutdate
FROM 	EPIC.eh_charge c, 
		EPIC.eh_booking b, 
		EPIC.eh_active_booking ab,
		EPIC.eh_charge_agency ca ,
     	EPIC.eh_case cs, 
     	EPIC.eh_case_charge cc, 
     	EPIC.eh_case_court cct,
     	EPIC.eh_entity_organization eo, 
     	EPIC.eh_sentence s, 
     	EPIC.eh_sentence_out_dates so,
     	EPIC.epic_statutes es, 
     	EPIC.eh_bail_condition bc, 
     	EPIC.eh_bail_condition_charge bcc,
		EPIC.eh_offender_ids id
WHERE b.booking_id = c.booking_id 
  AND c.charge_id = ca.charge_id 
  AND s.sentence_id (+) = c.sentence_id 
  AND cs.booking_id = b.booking_id 
  AND cc.charge_id = c.charge_id 
  AND cc.cASe_id = cs.cASe_id 
  AND cct.cASe_id = cs.cASe_id 
  AND eo.entity_id = ca.agency_id 
  AND es.STATUTE_ID = c.statute_id
  AND so.sentence_id (+)  = c.sentence_id
  AND bc.booking_id = b.booking_id
  AND bcc.charge_id = c.charge_id
  AND bc.bail_condition_id = bcc.bail_condition_id
  AND b.booking_id = ab.booking_id
  AND id.ENTITY_ID = ab.entity_id
  AND EPIC.ef_is_active_booking(b.entity_id)='TRUE'
union
-- HOLD records
SELECT EPIC.ef_offender_id(b.entity_id) AS entity_id,
       h.hold_id AS charge_id,
	   NULL      AS statute_id,
       NULL      AS pacc,
       NULL      AS charge_desc,
       EPIC.ef_lookup_text('STATUTE CLASS', code_charge_severity, 'UC') AS charge_clASs,
       NULL                 AS sentence_id,
       EPIC.ef_lookup_text('HOLD TYPE',code_hold_type,'UC') AS charge_id_number,
       h.agency_id          AS agency_id,
       eo.organization_name AS complaint_dept,
       NULL                 AS court_id,
       -- case number (other attrib - hold warant number)
       EPIC.ef_get_attribute_value('HOLD WARRANT NUMBER',h.hold_id) AS case_no,
       -- court name  (other attrib - hold court)
       EPIC.ef_get_attribute_value('HOLD COURT',h.hold_id) AS court_name,
       NULL AS court_date,
       NULL AS court_division,
       NULL AS court_judge,
       NULL AS start_date,
       NULL AS final_release_date,
       -- bond/fines  (other attrib - hold amount)
       to_number(EPIC.ef_get_attribute_value('HOLD AMOUNT',h.hold_id)) AS amount,
       'BOND' AS amount_type,
	   'H'    AS Trans_type,
       3      AS sortorder,
        EPIC.mcmb_fnt_offenderidfrombk(b.booking_id)||' - '||h.hold_id,
   	    decode(sign(instr(EPIC.ef_get_attribute_value('HOLD INFO',h.hold_id),'10%')+
  					instr(EPIC.ef_get_attribute_value('HOLD INFO',h.hold_id),'10 %')+
   					instr(upper(EPIC.ef_get_attribute_value('HOLD INFO',h.hold_id)),'10 PERCENT'))-
   					(instr(upper(EPIC.ef_get_attribute_value('HOLD INFO',h.hold_id)),'NO 10')*100)-
   					(instr(upper(EPIC.ef_get_attribute_value('HOLD INFO',h.hold_id)),'NO10')*100),
				  					1,'Y','N') AS reduceamount,
		NULL AS paidoutdate,
		NULL AS unpaidoutdate
FROM EPIC.eh_booking_holds h, 
     EPIC.eh_active_booking b,
     EPIC.eh_entity_organization eo
WHERE b.booking_id = h.booking_id 
  AND eo.entity_id = h.agency_id;


REM Note that this DDL is not guaranteed to include
REM   all properties of the original object.  It will also
REM   not include CLUSTER or PARTITION information.  Please
REM   report any other problems to support@benthicsoftware.com
CREATE OR REPLACE VIEW MCMB_VIEW_INMATE (ENTITY_ID, LASTNAME, FIRSTNAME, LEVEL4, LEVEL5, LEVEL6, LEVEL7, LEVEL8, DOB, PAID_RELEASE, PROJECTED_RELEASE, JUVENILE_FLAG, SENT_TOTAL, HOLD_TOTAL, BAIL_TOTAL, MUGPATH, VEHICLE_ID, TOW_COMPANY, OTHERNAME, INMATECLASS, GENDER, CELL, RESTRICTIONUNTIL) AS
select      id.OFFENDER_ID AS entity_id,
				pi.NAME_FAMILY as lastname,
			    pi.NAME_FIRST  as firstname,
	   		 substr(epic.ef_location_path_name(ha.location_id ,'uc',4),1,instr(epic.ef_location_path_name(ha.location_id ,'uc',4),',')-1) as Level4,
	   		 substr(epic.ef_location_path_name(ha.location_id ,'uc',5),1,instr(epic.ef_location_path_name(ha.location_id ,'uc',5),',')-1) as Level5,
	  		 substr(epic.ef_location_path_name(ha.location_id ,'uc',6),1,instr(epic.ef_location_path_name(ha.location_id ,'uc',6),',')-1) as Level6,
       		 substr(epic.ef_location_path_name(ha.location_id ,'uc',7),1,instr(epic.ef_location_path_name(ha.location_id ,'uc',7),',')-1) as level7,
       		 substr(epic.ef_location_path_name(ha.location_id ,'uc',8),
              instr(epic.ef_location_path_name(ha.location_id ,'uc',8),
        		/*level7 */ substr(epic.ef_location_path_name(ha.location_id ,'uc',7),1,instr(epic.ef_location_path_name(ha.location_id ,'uc',7),',')-1)
                    ,2)+1) as level8,
				NVL(NVL(to_char(epic.ef_epic_date_to_date(pi.DATE_OF_BIRTH),'MM/DD/YYYY'),
						to_char(epic.ef_epic_date_to_date(pi.BIRTH_DATE_APPROX),'MM/DD/YYYY')),
					'UNKNOWN_DOB') as DOB,
				epic.ef_epic_date_to_date(epic.epp_booking_dates.earliest_release_date(ab2.booking_id)) as paid_release,
    	   		epic.ef_epic_date_to_date(epic.epp_booking_dates.final_release_date(ab2.booking_id))    as Projected_release,--,
				decode(ep.JUVENILE_FLAG,'Y','Y','N') as juvenile_flag,
    	   		EPIC.mcmb_fnt_sent_Total_Amount(ab2.booking_id) as sent_total,
    	   		EPIC.mcmb_fnt_hold_Total_Amount(ab2.booking_id) as hold_total,
    	   		EPIC.mcmb_fnt_Bail_Total_Amount(ab2.booking_id) as bail_total,
				decode(ei.imageref, null,null,
					'\\' || ev.volumeserver || '\F$\FTP\' || ev.volumepath || '\' || ei.imageref) as mugpath,
   				vehicle_id as vehicle_id,
				eo.ORGANIZATION_NAME as tow_company,
				pi.NAME_OTHER  as othername,
	   		 decode(epic.ef_offender_CustStat(ab2.entity_id),
                  	'REGULAR INMATE','R',
					'WORK RELEASE','W',
                  	'KITCHEN TRUSTEE (White)','K',
                  	'GARAGE TRUSTEE (Orange)','O',
                  	'SPECIAL TRUSTEE (Green)','G',
                  	'R') as inmateclass,
   				decode(ep.CODE_GENDER,'_NOSP','U',ep.CODE_GENDER) as gender,
		   		 substr(epic.ef_location_name(ha.location_id ,'uc'),1,10) as cell,
    	   		epic.ef_epic_date_to_date(r.end_date) as restrictionuntil
			 from   epic.EH_OFFENDER_IDS id,
			 		epic.EH_PERSON_IDENTITY pi,
			 		epic.eh_entity_person ep,
			 		epic.EH_VEHICLE v,
					epic.EH_ENTITY_ORGANIZATION  eo,
					epic.Epicvolume ev,
					epic.Epicimage ei,
					epic.Eh_entity_default_photo ph,
					epic.eh_active_booking ab2,
					epic.eh_housing_assignments ha,
					epic.EH_ENTITY_RESTRICTION r
			 where  id.entity_id = ab2.entity_id
  			   and  epic.ef_is_active_booking(ab2.entity_id)='TRUE'
  			   and  id.entity_id = pi.entity_id
  			   and  id.entity_id = ep.entity_id
  			   and  ab2.entity_id = ha.entity_id
			   and  v.entity_id(+) = pi.entity_id
			   and  v.tow_company_id = eo.entity_id(+)
			   and  ei.imageref(+) = ph.photo_id
			   and  ev.volumeid(+) = ei.volumeid
			   and  ph.entity_id(+) = id.entity_id
  			   and  pi.code_name_type = 'MAS'
  			   and  ab2.entity_id = id.entity_id
  			   and  ab2.entity_id = r.entity_id(+);


REM Note that this DDL is not guaranteed to include
REM   all properties of the original object.  It will also
REM   not include CLUSTER or PARTITION information.  Please
REM   report any other problems to support@benthicsoftware.com
CREATE OR REPLACE VIEW MCMB_VIEW_VISTITOR (ENTITY_ID, VISITOR_ID, APPLICATION_DATE, EXPIRATION_DATE, LASTNAME, FIRSTNAME, STATUS, TYPESEQ, VISTITOR_PK) AS
SELECT 	id.offender_id AS entity_id, 
		er.ENTITY_RELATED_TO AS VISITOR_ID,
		DECODE(er.RELATIONSHIP_TYPE,'21',NVL(to_char(EPIC.ef_epic_date_to_date(EPIC.mcmb_fnt_Vist_app_date(er.ENTITY_RELATED_TO)),'MM/DD/YYYY'),'unknown'),null) AS application_date,
       	DECODE(er.RELATIONSHIP_TYPE,'21',NVL(to_char(EPIC.ef_epic_date_to_date(EPIC.mcmb_fnt_Vist_expir_date(er.ENTITY_RELATED_TO)),'MM/DD/YYYY'),'unknown'),null) AS expiration_date,
       	pi.name_family AS lastname,
       	pi.name_first  AS firstname,
       	DECODE(er.RELATIONSHIP_TYPE,'21','A','N') AS status,
       	DECODE(er.RELATIONSHIP_TYPE,'21','1','2') AS typeseq,
   	   	id.offender_id ||'-'||er.ENTITY_RELATED_TO AS vistitor_pk
FROM   	EPIC.eh_offender_ids id,
		EPIC.eh_person_identity pi,
       	EPIC.eh_entity_relationship er
--       	EPIC.eh_active_booking ab
WHERE  er.ENTITY_RELATED_TO = pi.entity_id
--  AND  ab.entity_id = pi.entity_id
  AND  id.entity_id = er.entity_id
  AND  er.related_as_role = 'VISTR'
  AND  pi.code_name_type = 'MAS'   
  AND EXISTS (select 1 from EPIC.eh_active_booking ab where pi.entity_id = ab.entity_id)
  
UNION
-- Banned
SELECT 	'' AS entity_id, 
		va.visitor_id AS vistitor_id, 
		va.date_FROM AS application_date, 
		va.date_to AS expiration_date, 
		vpi.name_family AS lastname, 
		vpi.name_first  AS firstname, 
		'B' AS status, 
		'3' AS typeseq,
		''||'-'||va.VISITOR_ID
FROM 	EPIC.eh_banned_visitor va, 
		EPIC.eh_person_identity vpi
--       	EPIC.eh_active_booking ab
WHERE 	va.visitor_id = vpi.entity_id
--  AND	ab.entity_id = vpi.entity_id
  AND EXISTS (select 1 from EPIC.eh_active_booking ab where vpi.entity_id = ab.entity_id);


REM Note that this DDL is not guaranteed to include
REM   all properties of the original object.  It will also
REM   not include CLUSTER or PARTITION information.  Please
REM   report any other problems to support@benthicsoftware.com
CREATE OR REPLACE VIEW MV_ACTIVE_ALIAS (ENTITY_ID, OFFENDER_ID, ALIAS_ID, LASTNAME, FIRSTNAME, MIDDLENAME, SUFFIXNAME, DOB, CODE_NAME_TYPE, LINK_PK) AS
select 	id.entity_id AS entity_id,
        id.OFFENDER_ID AS offender_id,
		pi.identity_id AS alias_id,
		pi.name_family AS lastname,
		pi.name_first  AS firstname,
		pi.name_other  AS middlename,
		pi.name_suffix AS suffixname,
 	    NVL(NVL(to_char(EPIC.ef_epic_date_to_date(pi.DATE_OF_BIRTH),'MM/DD/YYYY'),
 	    		to_char(EPIC.ef_epic_date_to_date(pi.BIRTH_DATE_APPROX),'MM/DD/YYYY')),
 	                   'UNKNOWN') AS DOB,
 	    pi.CODE_NAME_TYPE AS CODE_NAME_TYPE,
 	    decode(pi.CODE_NAME_TYPE, 'MAS',id.entity_id, 'ALIAS') AS LINK_PK
FROM    EPIC.eh_person_identity pi,
		EPIC.eh_offender_ids id
WHERE	id.ENTITY_ID = pi.entity_id
  AND	pi.CODE_NAME_TYPE in ('MAS','ALI')
  AND EXISTS (select 1 from EPIC.eh_active_booking ab where id.entity_id = ab.entity_id);


REM Note that this DDL is not guaranteed to include
REM   all properties of the original object.  It will also
REM   not include CLUSTER or PARTITION information.  Please
REM   report any other problems to support@benthicsoftware.com
CREATE OR REPLACE VIEW MV_ACTIVE_CHARGE (ENTITY_ID, OFFENDER_ID, CHARGE_ID, STATUTE_ID, PACC, CHARGE_DESC, CHARGE_CLASS, SENTENCE_ID, CHARGE_ID_NUMBER, AGENCY_ID, COMPLAINT_DEPT, COURT_ID, CASE_NO, COURT_NAME, COURT_DATE, COURT_DIVISION, COURT_JUDGE, START_DATE, FINAL_RELEASE_DATE, AMOUNT, AMOUNT_TYPE, TRANS_TYPE, SORTORDER, WEB_CHARGE_PK, REDUCEAMOUNT, PAIDOUTDATE, UNPAIDOUTDATE, SURCHARGE_AMOUNT, CHARGE_STATE) AS
SELECT 	b.entity_id                AS entity_id,
        id.OFFENDER_ID				AS offender_id,
		c.charge_id 				AS charge_id,
        c.statute_id 				AS statute_id,
        es.statute_number 			AS pacc,
        es.statute_description 		AS charge_desc,
    	EPIC.ef_lookup_text('STATUTE CLASS', es.code_statute_class, 'UC') AS charge_class,
        s.sentence_id 				AS sentence_id,
       	charge_id_number 			AS charge_id_number,
       	ca.agency_id 				AS agency_id,
       	eo.organization_name 		AS complaint_dept,
       	cct.court_id 				AS court_id,
       	cs.case_number 				AS case_no,
       	EPIC.mcmb_fnt_courtname(c.charge_id) AS court_name,
       	decode(
       	to_char(EPIC.ef_epic_date_to_date(EPIC.ef_next_court_date(b.entity_id)),'MM/DD/YYYY'),'12/25/2025','Call Court',
       	                                                                                      '01/01/2200','Call Court',
       	to_char(EPIC.ef_epic_date_to_date(EPIC.ef_next_court_date(b.entity_id)),'MM/DD/YYYY')) AS court_date,
       	EPIC.ef_next_court_division(b.entity_id) AS court_division,
       	EPIC.ef_lookup_text('JUDGE NAME',EPIC.ef_next_court_judge(b.entity_id),'UC') AS court_judge,
		EPIC.ef_epic_date_to_date(EPIC.epp_booking_dates.start_date(b.booking_id))         		AS Start_Date,
		EPIC.ef_epic_date_to_date(EPIC.epp_booking_dates.final_release_date(b.booking_id))     	AS final_releASe_date ,
		decode(c.sentence_id,NULL,
							to_number(bc.cash_only_bail_amount),
							to_number(EPIC.mcmb_fnt_fineamount(c.sentence_id)))  AS amount,
		decode(c.sentence_id,NULL, 'BAIL', 'FINE') AS amount_type,
		decode(c.sentence_id,NULL, 'U', 'S') AS Trans_type,
		decode(c.sentence_id,NULL, 2, 1) AS sortorder,
		EPIC.ef_offender_id(b.entity_id)||' - '||c.charge_id  AS web_charge_pk,
		decode(EPIC.ef_get_attribute_value('10 PERCENT BOND',bc.BAIL_CONDITION_ID),'YES',
															'Y',
															'N') AS reduceamount,
		EPIC.ef_epic_date_to_date(so.paid_out_date) AS paidoutdate,
		EPIC.ef_epic_date_to_date(so.unpaid_out_date) AS unpaidoutdate,
		bc.surcharge_amount  AS surcharge_amount,
		c.charge_state 
FROM 	EPIC.eh_charge c,                                               
		EPIC.eh_booking b, 
		EPIC.eh_active_booking ab,
		EPIC.eh_charge_agency ca ,
     	EPIC.eh_case cs, 
     	EPIC.eh_case_charge cc, 
     	EPIC.eh_case_court cct,
     	EPIC.eh_entity_organization eo, 
     	EPIC.eh_sentence s, 
     	EPIC.eh_sentence_out_dates so,
     	EPIC.epic_statutes es, 
     	EPIC.eh_bail_condition bc, 
     	EPIC.eh_bail_condition_charge bcc,
		EPIC.eh_offender_ids id
WHERE b.booking_id = c.booking_id 
  AND c.charge_id = ca.charge_id 
  AND s.sentence_id (+) = c.sentence_id 
  AND cs.booking_id = b.booking_id 
  AND cc.charge_id = c.charge_id 
  AND cc.cASe_id = cs.cASe_id 
  AND cct.cASe_id = cs.cASe_id 
  AND eo.entity_id = ca.agency_id 
  AND es.STATUTE_ID = c.statute_id
  AND so.sentence_id (+)  = c.sentence_id
  AND bc.booking_id = b.booking_id
  AND bcc.charge_id = c.charge_id
  AND bc.bail_condition_id = bcc.bail_condition_id
  AND b.booking_id = ab.booking_id
  AND id.ENTITY_ID = ab.entity_id
  AND EPIC.ef_is_active_booking(b.entity_id)='TRUE'
union
-- HOLD records
SELECT b.entity_id AS entity_id,
       EPIC.ef_offender_id(b.entity_id) AS offender_id,
       h.hold_id AS charge_id,
	   NULL      AS statute_id,
       NULL      AS pacc,
       NULL      AS charge_desc,
       EPIC.ef_lookup_text('STATUTE CLASS', code_charge_severity, 'UC') AS charge_clASs,
       NULL                 AS sentence_id,
       EPIC.ef_lookup_text('HOLD TYPE',code_hold_type,'UC') AS charge_id_number,
       h.agency_id          AS agency_id,
       eo.organization_name AS complaint_dept,
       NULL                 AS court_id,
       -- case number (other attrib - hold warant number)
       EPIC.ef_get_attribute_value('HOLD WARRANT NUMBER',h.hold_id) AS case_no,
       -- court name  (other attrib - hold court)
       EPIC.ef_get_attribute_value('HOLD COURT',h.hold_id) AS court_name,
       NULL AS court_date,
       NULL AS court_division,
       NULL AS court_judge,
       NULL AS start_date,
       NULL AS final_release_date,
       -- bond/fines  (other attrib - hold amount)
       to_number(EPIC.ef_get_attribute_value('HOLD AMOUNT',h.hold_id)) AS amount,
       'BOND' AS amount_type,
	   'H'    AS Trans_type,
       3      AS sortorder,
        EPIC.mcmb_fnt_offenderidfrombk(b.booking_id)||' - '||h.hold_id,
   	    decode(sign(instr(EPIC.ef_get_attribute_value('HOLD INFO',h.hold_id),'10%')+
  					instr(EPIC.ef_get_attribute_value('HOLD INFO',h.hold_id),'10 %')+
   					instr(upper(EPIC.ef_get_attribute_value('HOLD INFO',h.hold_id)),'10 PERCENT'))-
   					(instr(upper(EPIC.ef_get_attribute_value('HOLD INFO',h.hold_id)),'NO 10')*100)-
   					(instr(upper(EPIC.ef_get_attribute_value('HOLD INFO',h.hold_id)),'NO10')*100),
				  					1,'Y','N') AS reduceamount,
		NULL AS paidoutdate,
		NULL AS unpaidoutdate,
		NULL AS surcharge_amount,
		NULL AS charge_state
FROM EPIC.eh_booking_holds h, 
     EPIC.eh_active_booking b,
     EPIC.eh_entity_organization eo
WHERE b.booking_id = h.booking_id 
  AND eo.entity_id = h.agency_id;


REM Note that this DDL is not guaranteed to include
REM   all properties of the original object.  It will also
REM   not include CLUSTER or PARTITION information.  Please
REM   report any other problems to support@benthicsoftware.com
CREATE OR REPLACE VIEW MV_ACTIVE_INMATE (ENTITY_ID, OFFENDER_ID, LASTNAME, FIRSTNAME, LEVEL4, LEVEL5, LEVEL6, LEVEL7, LEVEL8, DOB, PAID_RELEASE, PROJECTED_RELEASE, JUVENILE_FLAG, SENT_TOTAL, HOLD_TOTAL, BAIL_TOTAL, MUGPATH, VEHICLE_ID, TOW_COMPANY, OTHERNAME, INMATECLASS, GENDER, CELL, RESTRICTIONUNTIL) AS
select      id.entity_id AS entity_id,
            id.OFFENDER_ID AS offender_id,
				pi.NAME_FAMILY as lastname,
			    pi.NAME_FIRST  as firstname,
	   		 substr(epic.ef_location_path_name(ha.location_id ,'uc',4),1,instr(epic.ef_location_path_name(ha.location_id ,'uc',4),',')-1) as Level4,
	   		 substr(epic.ef_location_path_name(ha.location_id ,'uc',5),1,instr(epic.ef_location_path_name(ha.location_id ,'uc',5),',')-1) as Level5,
	  		 substr(epic.ef_location_path_name(ha.location_id ,'uc',6),1,instr(epic.ef_location_path_name(ha.location_id ,'uc',6),',')-1) as Level6,
       		 substr(epic.ef_location_path_name(ha.location_id ,'uc',7),1,instr(epic.ef_location_path_name(ha.location_id ,'uc',7),',')-1) as level7,
       		 substr(epic.ef_location_path_name(ha.location_id ,'uc',8),
              instr(epic.ef_location_path_name(ha.location_id ,'uc',8),
        		/*level7 */ substr(epic.ef_location_path_name(ha.location_id ,'uc',7),1,instr(epic.ef_location_path_name(ha.location_id ,'uc',7),',')-1)
                    ,2)+1) as level8,
				NVL(NVL(to_char(epic.ef_epic_date_to_date(pi.DATE_OF_BIRTH),'MM/DD/YYYY'),
						to_char(epic.ef_epic_date_to_date(pi.BIRTH_DATE_APPROX),'MM/DD/YYYY')),
					'UNKNOWN_DOB') as DOB,
				epic.ef_epic_date_to_date(epic.epp_booking_dates.earliest_release_date(ab2.booking_id)) as paid_release,
    	   		epic.ef_epic_date_to_date(epic.epp_booking_dates.final_release_date(ab2.booking_id))    as Projected_release,--,
				decode(ep.JUVENILE_FLAG,'Y','Y','N') as juvenile_flag,
    	   		EPIC.mcmb_fnt_sent_Total_Amount(ab2.booking_id) as sent_total,
    	   		EPIC.mcmb_fnt_hold_Total_Amount(ab2.booking_id) as hold_total,
    	   		EPIC.mcmb_fnt_Bail_Total_Amount(ab2.booking_id) as bail_total,
				decode(ei.imageref, null,null,
					'\\' || ev.volumeserver || '\F$\FTP\' || ev.volumepath || '\' || ei.imageref) as mugpath,
   				vehicle_id as vehicle_id,
				eo.ORGANIZATION_NAME as tow_company,
				pi.NAME_OTHER  as othername,
	   		 decode(epic.ef_offender_CustStat(ab2.entity_id),
                  	'REGULAR INMATE','R',
					'WORK RELEASE','W',
                  	'KITCHEN TRUSTEE (White)','K',
                  	'GARAGE TRUSTEE (Orange)','O',
                  	'SPECIAL TRUSTEE (Green)','G',
                  	'R') as inmateclass,
   				decode(ep.CODE_GENDER,'_NOSP','U',ep.CODE_GENDER) as gender,
		   		 substr(epic.ef_location_name(ha.location_id ,'uc'),1,10) as cell,
    	   	(select max(epic.ef_epic_date_to_date(r.end_date)) from epic.EH_ENTITY_RESTRICTION r where ab2.entity_id = r.entity_id(+) and epic.ef_epic_date_to_date(r.end_date)>sysdate ) as restrictionuntil
			 from   epic.EH_OFFENDER_IDS id,
			 		epic.EH_PERSON_IDENTITY pi,
			 		epic.eh_entity_person ep,
			 		epic.EH_VEHICLE v,
					epic.EH_ENTITY_ORGANIZATION  eo,
					epic.Epicvolume ev,
					epic.Epicimage ei,
					epic.Eh_entity_default_photo ph,
					epic.eh_active_booking ab2,
					epic.eh_housing_assignments ha
			 where  id.entity_id = ab2.entity_id
  			   and  epic.ef_is_active_booking(ab2.entity_id)='TRUE'
  			   and  id.entity_id = pi.entity_id
  			   and  id.entity_id = ep.entity_id
  			   and  ab2.entity_id = ha.entity_id
			   and  v.entity_id(+) = pi.entity_id
			   and  v.tow_company_id = eo.entity_id(+)
			   and  ei.imageref(+) = ph.photo_id
			   and  ev.volumeid(+) = ei.volumeid
			   and  ph.entity_id(+) = id.entity_id
  			   and  pi.code_name_type = 'MAS'
  			   and  ab2.entity_id = id.entity_id;


REM Note that this DDL is not guaranteed to include
REM   all properties of the original object.  It will also
REM   not include CLUSTER or PARTITION information.  Please
REM   report any other problems to support@benthicsoftware.com
CREATE OR REPLACE VIEW MV_BOOKING_LOOKUPS (LOOKUP_CLASS, SUB_1, SUB_2, SUB_3, SUB_4, LOOKUP_CODE, TEXT_FULL, DISPLAY_ORDER) AS
SELECT LOOKUP_CLASS, SUB_1, SUB_2, SUB_3, SUB_4, LOOKUP_CODE, TEXT_FULL, display_order
FROM   EPIC.epic_lookups
WHERE  EFFECTIVE_END_DATE > EPIC.epicdatenow()
  AND  lookup_class IN ('NAME SUFFIX TYPE','STATES', 'RACE', 'SEX',
						'STAFF TITLE','EYE COLOUR', 'HAIR COLOUR',
                       'COMPLEXION', 'MARITAL STATUS', 'COUNTRY',
                       'LANGUAGE','LANGUAGE GRADING',
                       'RELATIONSHIP', 'RELATIONSHIP STATUS',
                       /*'RELATIONSHIP TYPE',*/ 'ALERT CATEGORY',
                       'PROPERTY LOCATION', 'CHARGE MODIFIER',
                       'ARREST REASON', 'COURT NAME',
                       'CPS EDUCATION LEVEL', 'ARRESTINGOFFICERS',
                       'MONTH', 'OCCUPATION', 'OWNING AGENCY',
                       'ORGANISATION ROLE', 'ORGANISATION TYPE',
                       'PROPERTY MATERIAL','PROPERTY TYPE',
                       'VEHICLE STORAGE', 'YES NO', 'YES NO NA',
                       'YES NO REFUSED','STATUTE CLASS', 'COLOUR TYPE', 'EDUCATION CLASS NAME', 'PERSONAL RELATIONSHIP' /*,'BUILD'*/ )
  
UNION
SELECT LOOKUP_CLASS, SUB_1, SUB_2, SUB_3, SUB_4, LOOKUP_CODE, TEXT_FULL, display_order
FROM   EPIC.epic_lookups
WHERE  EFFECTIVE_END_DATE > EPIC.epicdatenow()
  AND  lookup_class IN ('RELIGION') 
  AND  SUB_2 is not null;


REM Note that this DDL is not guaranteed to include
REM   all properties of the original object.  It will also
REM   not include CLUSTER or PARTITION information.  Please
REM   report any other problems to support@benthicsoftware.com
CREATE OR REPLACE VIEW MV_COURTS (ORGANIZATION_NAME, SORT, ENTITY_ID) AS
select o.organization_name,  -- 0 MCSO, 1 Macomb others, 3 near counties, 4 others
       decode(a.postal_code, '48041',1,'48043',0,'48045',2,'48046',1,
                             '48047',1,'48048',1,'48060',3,'48062',3,
                             '48091',1,'48089',1,'48021',1,'48080',1,
                             '48081',1,'48066',1,'48015',1,'48092',1,
                             '48093',1,'48026',1,'48082',1,'48045',1,
                             '48035',1,'48036',1,'48312',1,'48310',1,
                             '48314',1,'49313',1,'48038',1,'48036',1,
                             '48317',1,'48094',1,'48096',1,'48048',1,
                             '48051',1,'48047',1,'48094',1,'48095',1,
                             '48096',1,'48050',1,'48065',1,'48005',1,
                             '48062',1,'48065',1,'48066',1,'48067',3,
                             '48069',3,'48070',3,'48071',3,'48072',3,
                             '48076',3,'48076',3,'48084',3,'48226',3,
                             '48234',3,'48236',3,'48242',3,'48313',1,
                             '48316',1,'48079',3,'48081',3,'48093',3,
                             '48317',1,'48341',2,'48342',2,'48413',3,'48455',1,4),
       o.entity_id
from EPIC.EH_ENTITY_ORGANIZATION o,epic.eh_entity_roles r, epic.eh_address a
where r.code_entity_role in ('783')
  and o.entity_id = r.entity_id
  and r.effective_to >= EPIC.epicdatenow()
  and o.date_ceased_operating is null
  and o.entity_id = a.entity_id
order by 2, 1;


REM Note that this DDL is not guaranteed to include
REM   all properties of the original object.  It will also
REM   not include CLUSTER or PARTITION information.  Please
REM   report any other problems to support@benthicsoftware.com
CREATE OR REPLACE VIEW MV_EPIC_USER_NAMES (USER_INT_ID, USER_ID, ENCRYPTED_PASSWORD, USER_NAME_LAST, USER_NAME_FIRST, USER_NAME_MIDDLE, USER_NAME_SUFFIX, JOB_TITLE, DATE_START, DATE_END, TRAINING_ONLY_FLAG, DEFAULT_SERVICE, DEFAULT_LEVEL3, DEFAULT_LEVEL4, DEFAULT_LEVEL5, DEFAULT_LEVEL6, DEFAULT_LEVEL7, DEFAULT_LEVEL8, ACTION_TYPE, ACTION_TIME, ACTION_BY, EPIC_ID) AS
SELECT "USER_INT_ID","USER_ID","ENCRYPTED_PASSWORD","USER_NAME_LAST","USER_NAME_FIRST","USER_NAME_MIDDLE","USER_NAME_SUFFIX","JOB_TITLE","DATE_START","DATE_END","TRAINING_ONLY_FLAG","DEFAULT_SERVICE","DEFAULT_LEVEL3","DEFAULT_LEVEL4","DEFAULT_LEVEL5","DEFAULT_LEVEL6","DEFAULT_LEVEL7","DEFAULT_LEVEL8","ACTION_TYPE","ACTION_TIME","ACTION_BY","EPIC_ID"
FROM   EPIC.epic_user_names;


REM Note that this DDL is not guaranteed to include
REM   all properties of the original object.  It will also
REM   not include CLUSTER or PARTITION information.  Please
REM   report any other problems to support@benthicsoftware.com
CREATE OR REPLACE VIEW MV_ORGANIZATION (ORGANIZATION_NAME, SORT, ENTITY_ID) AS
select o.organization_name,  -- 0 MCSO, 1 Macomb others, 3 near counties, 4 others
       decode(a.postal_code, '48041',1,'48043',0,'48045',2,'48046',1,
                             '48047',1,'48048',1,'48060',3,'48062',3,
                             '48091',1,'48089',1,'48021',1,'48080',1,
                             '48081',1,'48066',1,'48015',1,'48092',1,
                             '48093',1,'48026',1,'48082',1,'48045',1,
                             '48035',1,'48036',1,'48312',1,'48310',1,
                             '48314',1,'49313',1,'48038',1,'48036',1,
                             '48317',1,'48094',1,'48096',1,'48048',1,
                             '48051',1,'48047',1,'48094',1,'48095',1,
                             '48096',1,'48050',1,'48065',1,'48005',1,
                             '48062',1,'48065',1,'48066',1,'48067',3,
                             '48069',3,'48070',3,'48071',3,'48072',3,
                             '48076',3,'48076',3,'48084',3,'48226',3,
                             '48234',3,'48236',3,'48242',3,'48313',1,
                             '48316',1,'48079',3,'48081',3,'48093',3,
                             '48317',1,'48341',2,'48342',2,'48413',3,'48455',1,4),
       o.entity_id
from EPIC.EH_ENTITY_ORGANIZATION o,epic.eh_entity_roles r, epic.eh_address a
where r.code_entity_role in ('784')
  and o.entity_id = r.entity_id
  and r.effective_to >= EPIC.epicdatenow()
  and o.date_ceased_operating is null
  and o.entity_id = a.entity_id
order by 2, 1;


REM Note that this DDL is not guaranteed to include
REM   all properties of the original object.  It will also
REM   not include CLUSTER or PARTITION information.  Please
REM   report any other problems to support@benthicsoftware.com
CREATE OR REPLACE VIEW MV_STATUTE (STATUTE_ID, STATUTE_NUMBER, STATUTE_DESCRIPTION, CODE_STATUTE_CLASS) AS
SELECT 	statute_id, 
		statute_number, 
		statute_description, 
		code_statute_class
FROM   	EPIC.epic_statutes s
WHERE  	(s.expiration_date >= EPIC.epicdatenow() 
   OR 	s.expiration_date IS NULL);


REM Note that this DDL is not guaranteed to include
REM   all properties of the original object.  It will also
REM   not include CLUSTER or PARTITION information.  Please
REM   report any other problems to support@benthicsoftware.com
CREATE OR REPLACE VIEW MV_VISTITOR (ENTITY_ID, OFFENDER_ID, VISITOR_ID, APPLICATION_DATE, EXPIRATION_DATE, LASTNAME, FIRSTNAME, STATUS, TYPESEQ, VISTITOR_PK) AS
SELECT 	id.entity_id AS entity_id,
        id.offender_id AS entity_id, 
		er.ENTITY_RELATED_TO AS VISITOR_ID,
		DECODE(er.RELATIONSHIP_TYPE,'21',NVL(to_char(EPIC.ef_epic_date_to_date(EPIC.mcmb_fnt_Vist_app_date(er.ENTITY_RELATED_TO)),'MM/DD/YYYY'),'unknown'),null) AS application_date,
       	DECODE(er.RELATIONSHIP_TYPE,'21',NVL(to_char(EPIC.ef_epic_date_to_date(EPIC.mcmb_fnt_Vist_expir_date(er.ENTITY_RELATED_TO)),'MM/DD/YYYY'),'unknown'),null) AS expiration_date,
       	pi.name_family AS lastname,
       	pi.name_first  AS firstname,
       	DECODE(er.RELATIONSHIP_TYPE,'21','A','N') AS status,
       	DECODE(er.RELATIONSHIP_TYPE,'21','1','2') AS typeseq,
   	   	id.offender_id ||'-'||er.ENTITY_RELATED_TO AS vistitor_pk
FROM   	EPIC.eh_offender_ids id,
		EPIC.eh_person_identity pi,
       	EPIC.eh_entity_relationship er
--       	EPIC.eh_active_booking ab
WHERE  er.ENTITY_RELATED_TO = pi.entity_id
--  AND  ab.entity_id = pi.entity_id
  AND  id.entity_id = er.entity_id
  AND  er.related_as_role = 'VISTR'
  AND  pi.code_name_type = 'MAS'   
  AND EXISTS (select 1 from EPIC.eh_active_booking ab where pi.entity_id = ab.entity_id)
  
UNION
-- Banned
SELECT 	'' AS entity_id, 
        '' AS offender_id,
		va.visitor_id AS vistitor_id, 
		va.date_FROM AS application_date, 
		va.date_to AS expiration_date, 
		vpi.name_family AS lastname, 
		vpi.name_first  AS firstname, 
		'B' AS status, 
		'3' AS typeseq,
		''||'-'||va.VISITOR_ID
FROM 	EPIC.eh_banned_visitor va, 
		EPIC.eh_person_identity vpi
--       	EPIC.eh_active_booking ab
WHERE 	va.visitor_id = vpi.entity_id
--  AND	ab.entity_id = vpi.entity_id
  AND EXISTS (select 1 from EPIC.eh_active_booking ab where vpi.entity_id = ab.entity_id);


REM
REM
REM
REM SEQUENCES
REM
REM
REM

REM Note that this DDL is not guaranteed to include
REM   all properties of the original object.  It will also
REM   not include CLUSTER or PARTITION information.  Please
REM   report any other problems to support@benthicsoftware.com
CREATE SEQUENCE PS_TXN_SEQ START WITH 21;

