
SELECT table_name
FROM SYS.ALL_TAB_COLUMNS
WHERE OWNER = 'EPIC'
  AND COLUMN_NAME = 'SENTENCE_ID';

select * from eh_offender_ids
where offender_id = '302031';  --entity_id = '0IR6B8O000USJ1IR'

select * from epic.eh_active_booking where entity_ID = '0IR6B8O000USJ1IR';
-- '0IR6BDI000USJ1IR'

select * from epic.eh_charge where booking_id = '0IR6BDI000USJ1IR';

select 'EH_ACTIVE_BOOKING'	 ,action_time from epic.EH_ACTIVE_BOOKING where entity_id = '0IR6B8O000USJ1IR'
union select 'EH_ACTIVE_MOVEMENT'	 ,action_time from epic.EH_ACTIVE_MOVEMENT where entity_id = '0IR6B8O000USJ1IR'
union select 'EH_ADDRESS'	 ,action_time from epic.EH_ADDRESS where entity_id = '0IR6B8O000USJ1IR'
union select 'EH_BACKGROUND_CHECK' ,action_time from epic.EH_BACKGROUND_CHECK	where entity_id = '0IR6B8O000USJ1IR'
union select 'EH_BAIL_PROCESSING_FEE'	 ,action_time from epic.EH_BAIL_PROCESSING_FEE	where entity_id = '0IR6B8O000USJ1IR'
union select 'EH_BILLING_ITEM', action_time from   epic.EH_BILLING_ITEM where entity_id = '0IR6B8O000USJ1IR'
union select 'EH_BOOKING'	 ,action_time from epic.EH_BOOKING where entity_id = '0IR6B8O000USJ1IR'
union select 'EH_CITIZENSHIP	'	 ,action_time from epic.EH_CITIZENSHIP	where entity_id = '0IR6B8O000USJ1IR'
union select 'EH_CURRENT_LOCATION'	, action_time from 	  epic.EH_CURRENT_LOCATION	where entity_id = '0IR6B8O000USJ1IR'
union select 'EH_DEPENDENTS'	 ,action_time from epic.EH_DEPENDENTS	where entity_id = '0IR6B8O000USJ1IR'
union select 'EH_ELECTRONIC_ADDRESS'	 ,action_time from epic.EH_ELECTRONIC_ADDRESS	where entity_id = '0IR6B8O000USJ1IR'
union select 'EH_ENTITY'	 ,action_time from epic.EH_ENTITY where entity_id = '0IR6B8O000USJ1IR'
union select 'EH_ENTITY_ALERTS'	 ,action_time from epic.EH_ENTITY_ALERTS where entity_id = '0IR6B8O000USJ1IR'
union select 'EH_ENTITY_ARTIFICIAL_AID'	 ,action_time from epic.EH_ENTITY_ARTIFICIAL_AID where entity_id = '0IR6B8O000USJ1IR'
union select 'EH_ENTITY_DEFAULT_PHOTO', action_time 	from 	  epic.EH_ENTITY_DEFAULT_PHOTO where entity_id = '0IR6B8O000USJ1IR'
--union select 'EH_ENTITY_DEFAULT_PHOTO_JEFF'	 ,action_time from epic.EH_ENTITY_DEFAULT_PHOTO_JEFF	 where entity_id = '0IR6B8O000USJ1IR'
union select 'EH_ENTITY_DEFORMITY', action_time 	from 	  epic.EH_ENTITY_DEFORMITY	 where entity_id = '0IR6B8O000USJ1IR'
union select 'EH_ENTITY_DISABILITY'	 ,action_time from epic.EH_ENTITY_DISABILITY	 where entity_id = '0IR6B8O000USJ1IR'
union select 'EH_ENTITY_EDUCATION', action_time 	from 	  epic.EH_ENTITY_EDUCATION	 where entity_id = '0IR6B8O000USJ1IR'
union select 'EH_ENTITY_EMPLOYMENT_INFO'	 ,action_time from epic.EH_ENTITY_EMPLOYMENT_INFO where entity_id = '0IR6B8O000USJ1IR'
union select 'EH_ENTITY_GENDER'	 ,action_time from epic.EH_ENTITY_GENDER where entity_id = '0IR6B8O000USJ1IR'
union select 'EH_ENTITY_HEIGHT'	 ,action_time from epic.EH_ENTITY_HEIGHT where entity_id = '0IR6B8O000USJ1IR'
union select 'EH_ENTITY_HI_EDUCATION'	 ,action_time from epic.EH_ENTITY_HI_EDUCATION	 where entity_id = '0IR6B8O000USJ1IR'
union select 'EH_ENTITY_INDIGENT'	 ,action_time from epic.EH_ENTITY_INDIGENT where entity_id = '0IR6B8O000USJ1IR'
union select 'EH_ENTITY_ORGANIZATION'	 ,action_time from epic.EH_ENTITY_ORGANIZATION	 where entity_id = '0IR6B8O000USJ1IR'
union select 'EH_ENTITY_PERSON'	 ,action_time from epic.EH_ENTITY_PERSON where entity_id = '0IR6B8O000USJ1IR'
union select 'EH_ENTITY_PHOTO'	, action_time from 	  epic.EH_ENTITY_PHOTO where entity_id = '0IR6B8O000USJ1IR'
union select 'EH_ENTITY_PHOTO_BOB'	, action_time from 	  epic.EH_ENTITY_PHOTO_BOB	 where entity_id = '0IR6B8O000USJ1IR'
union select 'EH_ENTITY_PHOTO_DARLENE', action_time 	from 	  epic.EH_ENTITY_PHOTO_DARLENE where entity_id = '0IR6B8O000USJ1IR'
--union select 'EH_ENTITY_PHOTO_JEFFBACKUP'	 ,action_time from epic.EH_ENTITY_PHOTO_JEFFBACKUP where entity_id = '0IR6B8O000USJ1IR'
union select 'EH_ENTITY_RACE'	 ,action_time from epic.EH_ENTITY_RACE	 where entity_id = '0IR6B8O000USJ1IR'
union select 'EH_ENTITY_RELATIONSHIP'	 ,action_time from epic.EH_ENTITY_RELATIONSHIP	 where entity_id = '0IR6B8O000USJ1IR'
union select 'EH_ENTITY_RELIGION'	 ,action_time from epic.EH_ENTITY_RELIGION where entity_id = '0IR6B8O000USJ1IR'
union select 'EH_ENTITY_RESTRICTION'	 ,action_time from epic.EH_ENTITY_RESTRICTION	 where entity_id = '0IR6B8O000USJ1IR'
union select 'EH_ENTITY_ROLES', action_time 	from 	  epic.EH_ENTITY_ROLES where entity_id = '0IR6B8O000USJ1IR'
union select 'EH_ENTITY_SMT'	 ,action_time from epic.EH_ENTITY_SMT	 where entity_id = '0IR6B8O000USJ1IR'
union select 'EH_ENTITY_STATUS'	 ,action_time from epic.EH_ENTITY_STATUS where entity_id = '0IR6B8O000USJ1IR'
union select 'EH_ENTITY_STRUCTURED_DAY'	 ,action_time from epic.EH_ENTITY_STRUCTURED_DAY where entity_id = '0IR6B8O000USJ1IR'
union select 'EH_ENTITY_WEIGHT'	 ,action_time from epic.EH_ENTITY_WEIGHT where entity_id = '0IR6B8O000USJ1IR'
union select 'EH_ENTITY_WORK_SKILLS'	 ,action_time from epic.EH_ENTITY_WORK_SKILLS	 where entity_id = '0IR6B8O000USJ1IR'
union select 'EH_ENT_DEF_PHOTO_DARLENE'	 ,action_time from epic.EH_ENT_DEF_PHOTO_DARLENE where entity_id = '0IR6B8O000USJ1IR'
union select 'EH_ESCAPED'	 ,action_time from epic.EH_ESCAPED where entity_id = '0IR6B8O000USJ1IR'
union select 'EH_ESCORTED_OUTING_APP'	 ,action_time from epic.EH_ESCORTED_OUTING_APP	 where entity_id = '0IR6B8O000USJ1IR'
union select 'EH_ESCORTED_OUTING_CHECKLIST'	 ,action_time from epic.EH_ESCORTED_OUTING_CHECKLIST	 where entity_id = '0IR6B8O000USJ1IR'
union select 'EH_ESCORT_OUT_INSTRUCTIONS'	 ,action_time from epic.EH_ESCORT_OUT_INSTRUCTIONS where entity_id = '0IR6B8O000USJ1IR'
union select 'EH_ETHNICITY'	 ,action_time from epic.EH_ETHNICITY	 where entity_id = '0IR6B8O000USJ1IR'
union select 'EH_EVENT_ENTITY_INSTANCE'	 ,action_time from epic.EH_EVENT_ENTITY_INSTANCE where entity_id = '0IR6B8O000USJ1IR'
union select 'EH_EXTERNAL_TRANSFER_APP'	 ,action_time from epic.EH_EXTERNAL_TRANSFER_APP where entity_id = '0IR6B8O000USJ1IR'
union select 'EH_EXTERNAL_TRAN_CHECKLIST'	 ,action_time from epic.EH_EXTERNAL_TRAN_CHECKLIST where entity_id = '0IR6B8O000USJ1IR'
union select 'EH_EXTERNAL_TRAN_INSTRUCTIONS'	 ,action_time from epic.EH_EXTERNAL_TRAN_INSTRUCTIONS	 where entity_id = '0IR6B8O000USJ1IR'
union select 'EH_FINGERPRINT'	 ,action_time from epic.EH_FINGERPRINT	 where entity_id = '0IR6B8O000USJ1IR'
union select 'EH_GANG_RELATIONSHIPS'	 ,action_time from epic.EH_GANG_RELATIONSHIPS	 where entity_id = '0IR6B8O000USJ1IR'
union select 'EH_GOOD_TIME_RATE_ASSIGN'	 ,action_time from epic.EH_GOOD_TIME_RATE_ASSIGN where entity_id = '0IR6B8O000USJ1IR'
union select 'EH_GRIEVANCE'	 ,action_time from epic.EH_GRIEVANCE	 where entity_id = '0IR6B8O000USJ1IR'
union select 'EH_GRIEVANCE_PERSON'	, action_time from 	  epic.EH_GRIEVANCE_PERSON	 where entity_id = '0IR6B8O000USJ1IR'
union select 'EH_HEALTH_ASSESS'	 ,action_time from epic.EH_HEALTH_ASSESS where entity_id = '0IR6B8O000USJ1IR'
union select 'EH_HEALTH_BLOOD_PRESSURE'	 ,action_time from epic.EH_HEALTH_BLOOD_PRESSURE where entity_id = '0IR6B8O000USJ1IR'
union select 'EH_HEALTH_BLOOD_RESULTS', action_time 	from 	  epic.EH_HEALTH_BLOOD_RESULTS where entity_id = '0IR6B8O000USJ1IR'
union select 'EH_HEALTH_CERVICAL_SMEAR'	 ,action_time from epic.EH_HEALTH_CERVICAL_SMEAR where entity_id = '0IR6B8O000USJ1IR'
union select 'EH_HEALTH_INITIAL_ASSESSMENT'	 ,action_time from epic.EH_HEALTH_INITIAL_ASSESSMENT	 where entity_id = '0IR6B8O000USJ1IR'
union select 'EH_HEALTH_MAMMOGRAM'	, action_time from 	  epic.EH_HEALTH_MAMMOGRAM	 where entity_id = '0IR6B8O000USJ1IR'
union select 'EH_HEALTH_PEAK_FLOW'	, action_time from 	  epic.EH_HEALTH_PEAK_FLOW	 where entity_id = '0IR6B8O000USJ1IR'
union select 'EH_HEALTH_URINE_ANALYSIS'	 ,action_time from epic.EH_HEALTH_URINE_ANALYSIS where entity_id = '0IR6B8O000USJ1IR'
union select 'EH_HEALTH_VISION'	 ,action_time from epic.EH_HEALTH_VISION where entity_id = '0IR6B8O000USJ1IR'
union select 'EH_HOUSING_ASSIGNMENTS'	 ,action_time from epic.EH_HOUSING_ASSIGNMENTS	 where entity_id = '0IR6B8O000USJ1IR'
union select 'EH_IDENTITY_IDS'	, action_time from 	  epic.EH_IDENTITY_IDS where entity_id = '0IR6B8O000USJ1IR'
union select 'EH_INCIDENT_CHARGE'	 ,action_time from epic.EH_INCIDENT_CHARGE where entity_id = '0IR6B8O000USJ1IR'
union select 'EH_INCIDENT_DESCRIPTION'	, action_time from 	  epic.EH_INCIDENT_DESCRIPTION where entity_id = '0IR6B8O000USJ1IR'
union select 'EH_INCIDENT_MINUTES'	, action_time from 	  epic.EH_INCIDENT_MINUTES	 where entity_id = '0IR6B8O000USJ1IR'
union select 'EH_INCIDENT_OFFENDER'	 ,action_time from epic.EH_INCIDENT_OFFENDER	 where entity_id = '0IR6B8O000USJ1IR'
union select 'EH_INCIDENT_OUTCOME'	, action_time from 	  epic.EH_INCIDENT_OUTCOME	 where entity_id = '0IR6B8O000USJ1IR'
union select 'EH_INCIDENT_SUBSTANCE_TEST'	 ,action_time from epic.EH_INCIDENT_SUBSTANCE_TEST where entity_id = '0IR6B8O000USJ1IR'
union select 'EH_INCIDENT_WITNESS'	, action_time from 	  epic.EH_INCIDENT_WITNESS	 where entity_id = '0IR6B8O000USJ1IR'
union select 'EH_JAIL_PROPERTY_NON_ISSUE'	 ,action_time from epic.EH_JAIL_PROPERTY_NON_ISSUE where entity_id = '0IR6B8O000USJ1IR'
union select 'EH_LANGUAGE'	, action_time from 	  epic.EH_LANGUAGE	 where entity_id = '0IR6B8O000USJ1IR'
union select 'EH_LOSS_PRIVILEGES'	 ,action_time from epic.EH_LOSS_PRIVILEGES where entity_id = '0IR6B8O000USJ1IR'
union select 'EH_MAIL_CORRESPONDENT'	 ,action_time from epic.EH_MAIL_CORRESPONDENT	 where entity_id = '0IR6B8O000USJ1IR'
union select 'EH_MARITAL_STATUS'	 ,action_time from epic.EH_MARITAL_STATUS where entity_id = '0IR6B8O000USJ1IR'
union select 'EH_MOVEMENT_TRANSFER'	 ,action_time from epic.EH_MOVEMENT_TRANSFER	 where entity_id = '0IR6B8O000USJ1IR'
union select 'EH_MUSTER'	 ,action_time from epic.EH_MUSTER where entity_id = '0IR6B8O000USJ1IR'
union select 'EH_OFFENDER_IDS'	, action_time from 	  epic.EH_OFFENDER_IDS where entity_id = '0IR6B8O000USJ1IR'
union select 'EH_OFFENDER_IDS_BAK'	, null from 	  epic.EH_OFFENDER_IDS_BAK	 where entity_id = '0IR6B8O000USJ1IR'
union select 'EH_OFFENDER_PROPERTY'	 ,action_time from epic.EH_OFFENDER_PROPERTY	 where entity_id = '0IR6B8O000USJ1IR'
union select 'EH_OFFENDER_VISIT_CONDITIONS'	 ,action_time from epic.EH_OFFENDER_VISIT_CONDITIONS	 where entity_id = '0IR6B8O000USJ1IR'
union select 'EH_OFF_GROUP_MEMBERS'	 ,action_time from epic.EH_OFF_GROUP_MEMBERS	 where entity_id = '0IR6B8O000USJ1IR'
union select 'EH_OPERATORS_LICENSE'	 ,action_time from epic.EH_OPERATORS_LICENSE	 where entity_id = '0IR6B8O000USJ1IR'
union select 'EH_PERSON_IDENTITY'	 ,action_time from epic.EH_PERSON_IDENTITY where entity_id = '0IR6B8O000USJ1IR'
union select 'EH_PERSON_SNAPSHOT'	 ,action_time from epic.EH_PERSON_SNAPSHOT where entity_id = '0IR6B8O000USJ1IR'
union select 'EH_PHONE_CALL'	 ,action_time from epic.EH_PHONE_CALL	 where entity_id = '0IR6B8O000USJ1IR'
union select 'EH_POSTED_ALERTS'	 ,action_time from epic.EH_POSTED_ALERTS where entity_id = '0IR6B8O000USJ1IR'
union select 'EH_RELATIONSHIP_EFFECTIVE'	 ,action_time from epic.EH_RELATIONSHIP_EFFECTIVE where entity_id = '0IR6B8O000USJ1IR'
union select 'EH_REQUEST'	 ,action_time from epic.EH_REQUEST where entity_id = '0IR6B8O000USJ1IR'
union select 'EH_RESERVATION_COMMENTS', action_time 	from 	  epic.EH_RESERVATION_COMMENTS where entity_id = '0IR6B8O000USJ1IR'
union select 'EH_RPT_CANREAD_TEMP', null 	from 	  epic.EH_RPT_CANREAD_TEMP	 where entity_id = '0IR6B8O000USJ1IR'
union select 'EH_STAFF_ASSIGNMENT', action_time 	from 	  epic.EH_STAFF_ASSIGNMENT	 where entity_id = '0IR6B8O000USJ1IR'
union select 'EH_TELEPHONE_RECORDS'	 ,action_time from epic.EH_TELEPHONE_RECORDS	 where entity_id = '0IR6B8O000USJ1IR'
union select 'EH_TEMPORARY_RELEASE_APP'	 ,action_time from epic.EH_TEMPORARY_RELEASE_APP where entity_id = '0IR6B8O000USJ1IR'
union select 'EH_TEMP_FIND_RESULTS'	 ,null from epic.EH_TEMP_FIND_RESULTS	 where entity_id = '0IR6B8O000USJ1IR'
union select 'EH_TEMP_GET_RECIPIENTS'	 ,null from epic.EH_TEMP_GET_RECIPIENTS	 where entity_id = '0IR6B8O000USJ1IR'
union select 'EH_TEMP_GROUP_BY_IDS'	 ,null from epic.EH_TEMP_GROUP_BY_IDS	 where entity_id = '0IR6B8O000USJ1IR'
union select 'EH_TEMP_NOTE_LIST'	 ,null from epic.EH_TEMP_NOTE_LIST where entity_id = '0IR6B8O000USJ1IR'
union select 'EH_TEMP_RELEASE_CHECKLIST'	 ,action_time from epic.EH_TEMP_RELEASE_CHECKLIST where entity_id = '0IR6B8O000USJ1IR'
union select 'EH_TEMP_RELEASE_SPEC_COND'	 ,action_time from epic.EH_TEMP_RELEASE_SPEC_COND where entity_id = '0IR6B8O000USJ1IR'
union select 'EH_TMP_GRIEVANCE_REGISTER'	 ,null from epic.EH_TMP_GRIEVANCE_REGISTER where entity_id = '0IR6B8O000USJ1IR'
union select 'EH_TMP_REQUEST_REGISTER', null 	from 	  epic.EH_TMP_REQUEST_REGISTER where entity_id = '0IR6B8O000USJ1IR'
union select 'EH_TRUST_ACCOUNT'	 ,action_time from epic.EH_TRUST_ACCOUNT where entity_id = '0IR6B8O000USJ1IR'
union select 'EH_VEHICLE'	 ,action_time from epic.EH_VEHICLE where entity_id = '0IR6B8O000USJ1IR'
union select 'EH_VIEWED_PHOTOS'	 ,action_time from epic.EH_VIEWED_PHOTOS where entity_id = '0IR6B8O000USJ1IR'
union select 'EH_VISITOR_ARR_DEPT', action_time 	from 	  epic.EH_VISITOR_ARR_DEPT	 where entity_id = '0IR6B8O000USJ1IR'
union select 'EH_VISIT_AUTHORIZATION'	 ,action_time from epic.EH_VISIT_AUTHORIZATION	 where entity_id = '0IR6B8O000USJ1IR'
union select 'EH_VISIT_SCHEDULE'	 ,action_time from epic.EH_VISIT_SCHEDULE where entity_id = '0IR6B8O000USJ1IR'
union select 'EH_VNR_NOTIFICATION', action_time 	from 	  epic.EH_VNR_NOTIFICATION	 where entity_id = '0IR6B8O000USJ1IR'
union select 'EH_VNR_STATUS'	 ,action_time from epic.EH_VNR_STATUS	 where entity_id = '0IR6B8O000USJ1IR'
union select 'EH_WORK_PROGRAM_APPL'	 ,action_time from epic.EH_WORK_PROGRAM_APPL	 where entity_id = '0IR6B8O000USJ1IR'
union select 'EH_WORK_PROG_ASSIGNMENT', action_time 	from 	  epic.EH_WORK_PROG_ASSIGNMENT where entity_id = '0IR6B8O000USJ1IR'
union select 'EH_WORK_PROG_ATTEND'	, action_time from 	  epic.EH_WORK_PROG_ATTEND	 where entity_id = '0IR6B8O000USJ1IR'
union select 'EPIC_EMAIL_MESSAGES', null 	from 	  epic.EPIC_EMAIL_MESSAGES	 where entity_id = '0IR6B8O000USJ1IR'
union select 'EPIC_FORM_INSTANCE'	 ,action_time from epic.EPIC_FORM_INSTANCE where entity_id = '0IR6B8O000USJ1IR'
union select 'EPIC_NOTIFICATION_ITEMS', null 	from 	  epic.EPIC_NOTIFICATION_ITEMS where entity_id = '0IR6B8O000USJ1IR'
union select 'EPIC_OFFENDER_LOG'	 ,action_time from epic.EPIC_OFFENDER_LOG where entity_id = '0IR6B8O000USJ1IR'
union select 'EPIC_TEMP_ACTIONS'	 ,null from epic.EPIC_TEMP_ACTIONS where entity_id = '0IR6B8O000USJ1IR'
union select 'EPIC_TEMP_VISITOR_SCHEDULE'	 ,null from epic.EPIC_TEMP_VISITOR_SCHEDULE where entity_id = '0IR6B8O000USJ1IR'
union select 'EPIC_TEMP_WKND_REPORT'	 ,null from epic.EPIC_TEMP_WKND_REPORT	 where entity_id = '0IR6B8O000USJ1IR'
union select 'EPIC_USER_JOBS'	 ,action_time from epic.EPIC_USER_JOBS	 where entity_id = '0IR6B8O000USJ1IR'
union select 'MG_NIST_MUGSHOT'	, action_time from 	  epic.MG_NIST_MUGSHOT where entity_id = '0IR6B8O000USJ1IR'
union select 'OTK_COM_TRANSACTIONS'	 ,action_time from epic.OTK_COM_TRANSACTIONS	 where entity_id = '0IR6B8O000USJ1IR'
union select 'OTK_ENTITY_CONTACTS'	, action_time from 	  epic.OTK_ENTITY_CONTACTS	 where entity_id = '0IR6B8O000USJ1IR'
union select 'OTK_PLAN_MEMBER'	, action_time from	  epic.OTK_PLAN_MEMBER where entity_id = '0IR6B8O000USJ1IR'
union select 'OTK_VENDOR_ID'	 ,action_time from epic.OTK_VENDOR_ID	 where entity_id = '0IR6B8O000USJ1IR'
union select 'SCG_MC_FORM6'	 ,action_time from epic.SCG_MC_FORM6	 where entity_id = '0IR6B8O000USJ1IR'
union select 'SCG_MC_WRISTBAND4'	 ,action_time from epic.SCG_MC_WRISTBAND4 where entity_id = '0IR6B8O000USJ1IR'
union select 'TEMP_COURT'	 ,null from epic.TEMP_COURT where entity_id = '0IR6B8O000USJ1IR'
union select 'TEMP_LEGACYBIN'	 ,null from epic.TEMP_LEGACYBIN	 where entity_id = '0IR6B8O000USJ1IR'
union select 'TEMP_SENTUPDATE', null from   epic.TEMP_SENTUPDATE where entity_id = '0IR6B8O000USJ1IR'
order by 2 desc;
--union select 'UNTITLED'	 ,action_time from epic.UNTITLED where entity_id = '0IR6B8O000USJ1IR'
--union select 'UNTITLED1'	 ,action_time from epic.UNTITLED1 where entity_id = '0IR6B8O000USJ1IR';


select 'EH_ACTIVE_BOOKING',action_time from EPIC.EH_ACTIVE_BOOKING  where booking_id = '0IR6BDI000USJ1IR'
union select 'EH_APPEAL',action_time from EPIC.EH_APPEAL	  where booking_id = '0IR6BDI000USJ1IR'
union select 'EH_BAIL_CONDITION',action_time from EPIC.EH_BAIL_CONDITION	  where booking_id = '0IR6BDI000USJ1IR'
union select 'EH_BOOKING',action_time from EPIC.EH_BOOKING  where booking_id = '0IR6BDI000USJ1IR'
union select 'EH_BOOKING_CUSTODY_STATUS',action_time from EPIC.EH_BOOKING_CUSTODY_STATUS	  where booking_id = '0IR6BDI000USJ1IR'
union select 'EH_BOOKING_DATA',action_time from EPIC.EH_BOOKING_DATA	  where booking_id = '0IR6BDI000USJ1IR'
union select 'EH_BOOKING_ENTITY_STATUS',action_time from EPIC.EH_BOOKING_ENTITY_STATUS	  where booking_id = '0IR6BDI000USJ1IR'
union select 'EH_BOOKING_HOLDS',action_time from EPIC.EH_BOOKING_HOLDS	  where booking_id = '0IR6BDI000USJ1IR'
union select 'EH_BOOKING_MANUAL_STATUS',action_time from EPIC.EH_BOOKING_MANUAL_STATUS	  where booking_id = '0IR6BDI000USJ1IR'
union select 'EH_BOOKING_OUT_DATES',action_time from EPIC.EH_BOOKING_OUT_DATES  where booking_id = '0IR6BDI000USJ1IR'
union select 'EH_BOOKING_RELEASE_DATES',action_time from EPIC.EH_BOOKING_RELEASE_DATES	  where booking_id = '0IR6BDI000USJ1IR'
union select 'EH_CASE',action_time from EPIC.EH_CASE	  where booking_id = '0IR6BDI000USJ1IR'
union select 'EH_CHARGE',action_time from EPIC.EH_CHARGE	  where booking_id = '0IR6BDI000USJ1IR'
union select 'EH_CHARGE_PRIMARY',action_time from EPIC.EH_CHARGE_PRIMARY	  where booking_id = '0IR6BDI000USJ1IR'
union select 'EH_ENTITY_ARREST_INCIDENT',action_time from EPIC.EH_ENTITY_ARREST_INCIDENT	  where booking_id = '0IR6BDI000USJ1IR'
union select 'EH_GOOD_TIME_RATE_ASSIGN',action_time from EPIC.EH_GOOD_TIME_RATE_ASSIGN	  where booking_id = '0IR6BDI000USJ1IR'
union select 'EH_MAIL_LOGGING',action_time from EPIC.EH_MAIL_LOGGING	  where booking_id = '0IR6BDI000USJ1IR'
union select 'EH_PHONE_CALL',action_time from EPIC.EH_PHONE_CALL  where booking_id = '0IR6BDI000USJ1IR'
union select 'EH_RELEASE',action_time from EPIC.EH_RELEASE  where booking_id = '0IR6BDI000USJ1IR'
union select 'EH_SECURITY_CLASSIFICATION',action_time from EPIC.EH_SECURITY_CLASSIFICATION  where booking_id = '0IR6BDI000USJ1IR'
union select 'EH_SENTENCE_POSTING',action_time from EPIC.EH_SENTENCE_POSTING  where booking_id = '0IR6BDI000USJ1IR'
union select 'EH_SERVICE_DELIVERY',action_time from EPIC.EH_SERVICE_DELIVERY  where booking_id = '0IR6BDI000USJ1IR'
union select 'EH_WATCH_ASSIGNMENT',action_time from EPIC.EH_WATCH_ASSIGNMENT  where booking_id = '0IR6BDI000USJ1IR'
union select 'EH_WEEKENDER_EPISODE',action_time from EPIC.EH_WEEKENDER_EPISODE  where booking_id = '0IR6BDI000USJ1IR'
union select 'EH_WEEKENDER_PERIOD',action_time from EPIC.EH_WEEKENDER_PERIOD  where booking_id = '0IR6BDI000USJ1IR'
order by 2 desc;

select     'EH_APPEAL',action_time from EPIC.EH_APPEAL	  where charge_id in ('0IR6BG8000USJ1IR','0IR6BRT000USJ1IR')
union select 'EH_BAIL_CONDITION_CHARGE',action_time from EPIC.EH_BAIL_CONDITION_CHARGE  where charge_id in ('0IR6BG8000USJ1IR','0IR6BRT000USJ1IR')
union select 'EH_CASE_CHARGE',action_time from EPIC.EH_CASE_CHARGE  where charge_id in ('0IR6BG8000USJ1IR','0IR6BRT000USJ1IR')
union select 'EH_CHARGE',action_time from EPIC.EH_CHARGE	  where charge_id in ('0IR6BG8000USJ1IR','0IR6BRT000USJ1IR')
union select 'EH_CHARGE_AGENCY',action_time from EPIC.EH_CHARGE_AGENCY	  where charge_id in ('0IR6BG8000USJ1IR','0IR6BRT000USJ1IR')
union select 'EH_CHARGE_CHANGE',action_time from EPIC.EH_CHARGE_CHANGE  where charge_id in ('0IR6BG8000USJ1IR','0IR6BRT000USJ1IR')
union select 'EH_CHARGE_PRIMARY',action_time from EPIC.EH_CHARGE_PRIMARY  where charge_id in ('0IR6BG8000USJ1IR','0IR6BRT000USJ1IR')
union select 'EH_INCIDENT_CHARGE',action_time from EPIC.EH_INCIDENT_CHARGE  where charge_id in ('0IR6BG8000USJ1IR','0IR6BRT000USJ1IR')
order by 2 desc;

select     'EH_CHARGE',action_time from EPIC.EH_CHARGE	 where sentence_id = '0IR6BSXTR0USJZ10'
union select 'EH_FINE_PAYMENT', action_time 	from EPIC.EH_FINE_PAYMENT  where sentence_id = '0IR6BSXTR0USJZ10'
union select 'EH_SENTENCE',action_time from EPIC.EH_SENTENCE	 where sentence_id = '0IR6BSXTR0USJZ10'
union select 'EH_SENTENCE_ADJUSTMENT' ,action_time	from EPIC.EH_SENTENCE_ADJUSTMENT	 where sentence_id = '0IR6BSXTR0USJZ10'
union select 'EH_SENTENCE_DATA',action_time from EPIC.EH_SENTENCE_DATA 	where sentence_id = '0IR6BSXTR0USJZ10'
union select 'EH_SENTENCE_FINE',action_time from EPIC.EH_SENTENCE_FINE	where sentence_id = '0IR6BSXTR0USJZ10'
union select 'EH_SENTENCE_OUT_DATES' , action_time	from EPIC.EH_SENTENCE_OUT_DATES	where sentence_id = '0IR6BSXTR0USJZ10'
order by 2 desc;



sentence_id = '0IR6BSXTR0USJZ10'
