CREATE OR REPLACE
TRIGGER TRG_ON_UPDATE_INMATES
 BEFORE UPDATE OF NAME_FIRST,NAME_OTHER,NAME_FAMILY,STREET,CITY_TOWN_LOCALE,STATE_PROVINCE_REGION,POSTAL_CODE,PHONE_NUMBER,ALTERNATIVE_PHONE_NUMBER,DATE_OF_BIRTH,SOCIAL_SECURITY_NUMBER,DRIVERS_LICENSE_NUMBER ON INMATES 
FOR EACH ROW 
DECLARE  count_rows NUMBER := 0;
BEGIN 
  --select count(*) into count_rows 
  --from INMATES_ADDRESS_HISTORY iah
  --where iah.OFFENDER_ID = :old.OFFENDER_ID;
 
  --if(count_rows = 0) then
  BEGIN
        insert into INMATES_ADDRESS_HISTORY
        (OFFENDER_ID, STREET, CITY_TOWN_LOCALE, STATE_PROVINCE_REGION, POSTAL_CODE, PHONE_NUMBER, 
         ALTERNATIVE_PHONE_NUMBER, DATE_OF_BIRTH, SOCIAL_SECURITY_NUMBER, DRIVERS_LICENSE_NUMBER, MODIFIED_BY, MODIFIED_DATE, NAME_FIRST, NAME_OTHER, NAME_FAMILY)
        values (:old.OFFENDER_ID, :old.STREET, :old.CITY_TOWN_LOCALE, :old.STATE_PROVINCE_REGION, :old.POSTAL_CODE, :old.PHONE_NUMBER,
                :old.ALTERNATIVE_PHONE_NUMBER, :old.DATE_OF_BIRTH, :old.SOCIAL_SECURITY_NUMBER, :old.DRIVERS_LICENSE_NUMBER, :old.MODIFIED_BY, decode(:old.MODIFIED_DATE,null,sysdate,:old.MODIFIED_DATE), :old.NAME_FIRST, :old.NAME_OTHER, :old.NAME_FAMILY);
  EXCEPTION WHEN DUP_VAL_ON_INDEX THEN --else
        update INMATES_ADDRESS_HISTORY 
        set STREET = :old.STREET,
        CITY_TOWN_LOCALE = :old.CITY_TOWN_LOCALE,
        STATE_PROVINCE_REGION = :old.STATE_PROVINCE_REGION,
        POSTAL_CODE = :old.POSTAL_CODE,
        PHONE_NUMBER = :old.PHONE_NUMBER, 
        ALTERNATIVE_PHONE_NUMBER = :old.ALTERNATIVE_PHONE_NUMBER,
        DATE_OF_BIRTH = :old.DATE_OF_BIRTH,
        SOCIAL_SECURITY_NUMBER = :old.SOCIAL_SECURITY_NUMBER,
        DRIVERS_LICENSE_NUMBER = :old.DRIVERS_LICENSE_NUMBER,
        MODIFIED_BY = :old.MODIFIED_BY,
        MODIFIED_DATE = :old.MODIFIED_DATE,
        NAME_FIRST = :old.NAME_FIRST,
        NAME_OTHER = :old.NAME_OTHER,
        NAME_FAMILY = :old.NAME_FAMILY
        where OFFENDER_ID = :old.OFFENDER_ID;
  END;  --end if;
END;
/
