CREATE TABLE pp_OFFTRK_IMPORT_BATCHES
AS SELECT * FROM OFFTRK_IMPORT_BATCHES;

CREATE TABLE pp_OFFTRK_IMPORT_CHARGE_LOG
AS SELECT * FROM OFFTRK_IMPORT_CHARGE_LOG;

CREATE TABLE pp_OFFTRK_IMPORT_INMATE_LOG
AS SELECT * FROM OFFTRK_IMPORT_INMATE_LOG;

CREATE TABLE pp_CHARGE_DETAIL
AS SELECT * FROM CHARGE_DETAIL;

CREATE TABLE pp_CHARGES
AS SELECT * FROM CHARGES;

CREATE TABLE pp_TRANSACTION_LOG
AS SELECT * FROM TRANSACTION_LOG;


CREATE TABLE pp_INMATES
AS SELECT * FROM INMATES;

CREATE TABLE pp_INMATES_ADDRESS_HISTORY
AS SELECT * FROM INMATES_ADDRESS_HISTORY;

CREATE TABLE pp_INMATES_STMT_INFO
AS SELECT * FROM INMATES_STMT_INFO;

CREATE SEQUENCE pp_TRANSACTIONLOG_SEQ
    MINVALUE 1
    MAXVALUE 999999999999999999999999999
    START WITH 1
    INCREMENT BY 1
    CACHE 20;

drop SEQUENCE pp_import_batches;
CREATE SEQUENCE pp_import_batches
    MINVALUE 1000
    MAXVALUE 999999999999999999999999999
    START WITH 1000
    INCREMENT BY 1
    CACHE 20;


select * from PP_OFFTRK_IMPORT_BATCHES;
delete from PP_OFFTRK_IMPORT_BATCHES;
delete from PP_OFFTRK_IMPORT_CHARGE_LOG;
delete from PP_OFFTRK_IMPORT_INMATE_LOG;
